{{- if eq (include "cerberus.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cerberus.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cerberus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.clickhouse.passwordKey }}: {{ .Values.clickhouse.password | quote }}
{{- end }}
