package regression

import (
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// #2341 split the `cardinality` golden shard's own regeneration out of
// update-golden.yml's ordinary one-row-per-shard `regenerate` matrix and into
// its own CI matrix: `cardinality-leg` (N runners, one leg each) closed by
// `cardinality-seal` (applies every leg's patch, re-asserts
// TestCardinalityBaselineCoversTheCorpus, and produces the one
// `golden-patch-cardinality` artifact `publish` already expected). This
// mirrors mutation.yml's `mutate` (per-phase matrix) / `mutation` (aggregator)
// shape, and this file is that lane's analogue of perf_guards_gate_test.go:
// it pins the wiring a PR diff can silently break, none of which shows up as
// a compile error or a passing local run.
//
// post-merge-drift.yml (#2635) mirrors the identical `cardinality-leg`/
// `cardinality-seal` split for the same reason update-golden.yml has it: the
// cardinality shard's regeneration is the one that most needs CI-matrix
// parallelism, whichever workflow is driving it. The two workflows diverge
// only past the seal: update-golden.yml's seal produces a `golden-patch-
// cardinality` artifact for `publish` to push, while post-merge-drift.yml's
// seal has nothing to publish — it diffs the sealed tree against `main` in
// place, reusing post-merge-golden-drift.mjs's own regenerate-and-diff mode
// with the regeneration itself skipped (the legs already did it). Every test
// below is parametrised over `cardinalityWorkflows` so a change to either
// workflow's cardinality split is pinned the same way.
const (
	updateGoldenWorkflowPath   = "../../.github/workflows/update-golden.yml"
	postMergeDriftWorkflowPath = "../../.github/workflows/post-merge-drift.yml"

	cardinalityLegJob  = "cardinality-leg"
	cardinalitySealJob = "cardinality-seal"
	// publishJob ("publish") is already declared package-wide by
	// release_gate_test.go; reused here rather than redeclared.

	// The runner behind both new jobs' profiling/sealing step (#2341's
	// MODE=leg / MODE=seal additions to the same script the LOCAL recipe
	// already used, see cardinality-baseline-update.mjs).
	cardinalityUpdateScript = "cardinality-baseline-update.mjs"

	// The env wiring a leg carries. PERF_SHARD_COUNT must come from
	// `strategy.job-total` (the number of legs that actually run), never a
	// repeated literal — exactly the perf-guards-shard precedent this mirrors:
	// a count left behind after the `leg:` list changed leaves part of the
	// corpus profiled by no leg, and every leg still reports green.
	cardinalityLegModeExpr        = "MODE: leg"
	cardinalitySealModeExpr       = "MODE: seal"
	cardinalityPerfShardIndexExpr = "PERF_SHARD_INDEX: ${{ matrix.leg }}"
	cardinalityPerfShardCountExpr = "PERF_SHARD_COUNT: ${{ strategy.job-total }}"

	// The artifact name `publish` already downloads via its unmodified
	// `golden-patch-*` pattern — update-golden.yml's cardinality-seal has to
	// keep producing exactly this name, or `publish` silently stops finding
	// cardinality's regenerated bytes and pushes without them. Only checked
	// for a workflow whose `cardinalityWorkflow.hasPublish` is true.
	cardinalityPatchArtifactName = "name: golden-patch-cardinality"

	// post-merge-drift.yml has no `publish` to feed — its cardinality-seal
	// diffs the sealed tree in place instead, by reusing post-merge-golden-
	// drift.mjs's default (regenerate-and-diff) mode with the regeneration
	// half turned off. Only checked for a workflow whose `hasPublish` is
	// false.
	postMergeDriftRunnerScript        = "post-merge-golden-drift.mjs"
	postMergeDriftSkipRegenerateExpr  = "POST_MERGE_SKIP_REGENERATE: '1'"
	postMergeDriftCardinalityShardEnv = "POST_MERGE_SHARDS: cardinality"
)

// cardinalityWorkflow names one workflow that carries the cardinality-leg /
// cardinality-seal split, and which of the checks below apply to it.
type cardinalityWorkflow struct {
	path string
	// hasPublish is true only for update-golden.yml, whose cardinality-seal
	// feeds a `publish` job that pushes the sealed patch as a `golden-patch-
	// cardinality` artifact. post-merge-drift.yml has no publish step — it
	// diffs the sealed tree in place and never uploads it anywhere.
	hasPublish bool
}

func (w cardinalityWorkflow) name() string { return filepath.Base(w.path) }

var cardinalityWorkflows = []cardinalityWorkflow{
	{path: updateGoldenWorkflowPath, hasPublish: true},
	{path: postMergeDriftWorkflowPath, hasPublish: false},
}

// The leg matrix list, e.g. `        leg: [1, 2, 3, 4, 5, 6, 7, 8]`.
var cardinalityLegMatrixListRe = regexp.MustCompile(`(?m)^\s*leg:\s*\[([0-9,\s]*)\]\s*$`)

// TestCardinalityLegAndSealJobsExist pins that the split actually exists as
// two named jobs a dependent job can wait on, and that whichever job consumes
// the sealed result (update-golden.yml's `publish`, post-merge-drift.yml's own
// diff-and-report step) is wired to wait for it rather than the OLD
// single-row shard or a leg that never finished.
func TestCardinalityLegAndSealJobsExist(t *testing.T) {
	t.Parallel()

	for _, wf := range cardinalityWorkflows {
		t.Run(wf.name(), func(t *testing.T) {
			t.Parallel()

			workflow := readFileString(t, wf.path)

			legJob := workflowJobBody(t, workflow, cardinalityLegJob)
			sealJob := workflowJobBody(t, workflow, cardinalitySealJob)

			if !strings.Contains(sealJob, "needs: [plan, "+cardinalityLegJob+"]") {
				t.Errorf("%s job %q does not declare `needs: [plan, %s]` — without that edge the seal can "+
					"run before every leg has written its slice, and \"every leg exited 0\" stops being "+
					"what it asserts.\nBody:\n%s", wf.path, cardinalitySealJob, cardinalityLegJob, sealJob)
			}

			if wf.hasPublish {
				publish := workflowJobBody(t, workflow, publishJob)
				if !strings.Contains(publish, cardinalitySealJob) {
					t.Errorf("%s job %q no longer mentions %q. `publish` has to wait for the sealed "+
						"cardinality patch (or its legitimate skip) before pushing, or a dispatch that "+
						"selected `cardinality` can publish every OTHER shard while silently dropping "+
						"cardinality's regeneration.\nBody:\n%s",
						wf.path, publishJob, cardinalitySealJob, publish)
				}
			} else {
				if !strings.Contains(sealJob, postMergeDriftRunnerScript) {
					t.Errorf("%s job %q does not run %s — the sealed tree is never diffed against what "+
						"landed, so a drifted cardinality baseline would seal clean and report nothing."+
						"\nBody:\n%s", wf.path, cardinalitySealJob, postMergeDriftRunnerScript, sealJob)
				}
			}

			for _, job := range []struct{ name, body string }{
				{cardinalityLegJob, legJob},
				{cardinalitySealJob, sealJob},
			} {
				if strings.Contains(job.body, continueOnError) {
					t.Errorf("%s job %q sets %s — a leg or the seal keeps its name and its logs while "+
						"losing its verdict, which is strictly worse than not gating at all: the "+
						"regenerated (or unsealed) bytes would still get treated as good.\nBody:\n%s",
						wf.path, job.name, continueOnError, job.body)
				}
			}
		})
	}
}

// TestCardinalityLegMatrixCoversEverySlice pins the shape of the CI-job
// partition against the SAME productionShardCount every other cardinality
// fan-out (the local recipe, the gating perf-guards-shard matrix) is measured
// at — see cardinality_baseline_fanout_test.go's identical concern for the
// local recipe side of this same constant.
func TestCardinalityLegMatrixCoversEverySlice(t *testing.T) {
	t.Parallel()

	for _, wf := range cardinalityWorkflows {
		t.Run(wf.name(), func(t *testing.T) {
			t.Parallel()

			legJob := workflowJobBody(t, readFileString(t, wf.path), cardinalityLegJob)

			list := cardinalityLegMatrixListRe.FindStringSubmatch(legJob)
			if list == nil {
				t.Fatalf("%s job %q declares no `leg: [...]` matrix list. The lane is split into CI jobs "+
					"precisely so it stops paying its wall-clock as one number; a matrix that stopped "+
					"fanning out reads as the split still being in effect while the job runs everything "+
					"serially again.\nBody:\n%s", wf.path, cardinalityLegJob, legJob)
			}

			var legs []int
			for _, field := range strings.Split(list[1], ",") {
				field = strings.TrimSpace(field)
				if field == "" {
					continue
				}
				n, err := strconv.Atoi(field)
				if err != nil {
					t.Fatalf("%s job %q has a non-integer leg %q in `leg: [%s]`",
						wf.path, cardinalityLegJob, field, list[1])
				}
				legs = append(legs, n)
			}

			sort.Ints(legs)
			want := make([]int, 0, len(legs))
			for i := range legs {
				want = append(want, i+1)
			}
			if intsString(legs) != intsString(want) {
				t.Errorf("%s job %q declares legs %v, which is not the contiguous 1..%d PERF_SHARD_INDEX "+
					"needs. An index outside [1, %d] profiles a slice that does not exist, and some slice "+
					"that does exist is profiled by nobody — with every leg green.",
					wf.path, cardinalityLegJob, legs, len(legs), len(legs))
			}

			partitionTest := readFileString(t, shardPartitionTestPath)
			declared := productionShardCountRe.FindStringSubmatch(partitionTest)
			if declared == nil {
				t.Fatalf("%s declares no `const productionShardCount` — the partition's coverage and "+
					"balance assertions no longer say which shard count they hold at", shardPartitionTestPath)
			}
			asserted, err := strconv.Atoi(declared[1])
			if err != nil {
				t.Fatalf("%s productionShardCount = %q is not an integer", shardPartitionTestPath, declared[1])
			}
			if asserted != len(legs) {
				t.Errorf("%s dispatches %d cardinality-leg jobs but %s asserts the partition's coverage, "+
					"disjointness and balance at %d. Those properties then hold for a partition CI never "+
					"runs this way: the split that ships is unmeasured, and the split that is measured "+
					"never ships.", wf.path, len(legs), shardPartitionTestPath, asserted)
			}
		})
	}
}

// TestCardinalityLegAndSealWireTheRunnerScript pins the env contract between
// each workflow and cardinality-baseline-update.mjs's MODE=leg / MODE=seal —
// the CI-matrix analogue of TestCardinalityFanOutMatchesTheGoPartition's
// local-recipe pin. Rename either side and the job still "runs", `go test`
// silently no-ops on an unmatched `-run` pattern (exit 0), and the lane
// reports a complete regeneration that touched nothing.
func TestCardinalityLegAndSealWireTheRunnerScript(t *testing.T) {
	t.Parallel()

	for _, wf := range cardinalityWorkflows {
		t.Run(wf.name(), func(t *testing.T) {
			t.Parallel()

			workflow := readFileString(t, wf.path)
			legJob := workflowJobBody(t, workflow, cardinalityLegJob)
			sealJob := workflowJobBody(t, workflow, cardinalitySealJob)

			if !strings.Contains(legJob, cardinalityUpdateScript) {
				t.Errorf("%s job %q no longer runs %s — nothing under this job actually profiles a corpus "+
					"slice.\nBody:\n%s", wf.path, cardinalityLegJob, cardinalityUpdateScript, legJob)
			}
			if !strings.Contains(sealJob, cardinalityUpdateScript) {
				t.Errorf("%s job %q no longer runs %s — nothing under this job asserts the legs together "+
					"covered the corpus.\nBody:\n%s", wf.path, cardinalitySealJob, cardinalityUpdateScript, sealJob)
			}

			for _, want := range []string{cardinalityLegModeExpr, cardinalityPerfShardIndexExpr, cardinalityPerfShardCountExpr} {
				if !strings.Contains(legJob, want) {
					t.Errorf("%s job %q does not wire `%s`. Without UPDATE_CARDINALITY_BASELINE's callers "+
						"(MODE=leg) and the exact PERF_SHARD_INDEX/PERF_SHARD_COUNT pair, the leg either "+
						"asserts instead of regenerating or profiles a slice that does not match the count "+
						"the partition actually divides by.\nBody:\n%s", wf.path, cardinalityLegJob, want, legJob)
				}
			}
			if !strings.Contains(sealJob, cardinalitySealModeExpr) {
				t.Errorf("%s job %q does not wire `%s` — without it the closing step either regenerates "+
					"(a check that rewrites what it checks cannot fail) or runs the wrong test.\nBody:\n%s",
					wf.path, cardinalitySealJob, cardinalitySealModeExpr, sealJob)
			}

			if wf.hasPublish {
				if !strings.Contains(sealJob, cardinalityPatchArtifactName) {
					t.Errorf("%s job %q does not upload an artifact named %q. `publish`'s own "+
						"`golden-patch-*` download pattern is unmodified by #2341 specifically because "+
						"this name has to match it exactly — rename it here and `publish` silently pushes "+
						"every other shard while dropping cardinality's regeneration.\nBody:\n%s",
						wf.path, cardinalitySealJob, cardinalityPatchArtifactName, sealJob)
				}
			} else {
				for _, want := range []string{postMergeDriftSkipRegenerateExpr, postMergeDriftCardinalityShardEnv} {
					if !strings.Contains(sealJob, want) {
						t.Errorf("%s job %q does not wire `%s`. Without POST_MERGE_SKIP_REGENERATE=1 the "+
							"diff-and-report step would re-run the WHOLE cardinality regeneration serially "+
							"a second time — the exact wall-clock cost the leg matrix exists to avoid — and "+
							"without POST_MERGE_SHARDS=cardinality it would fall back to deriving the "+
							"implied set itself instead of reporting on the one shard this job sealed."+
							"\nBody:\n%s", wf.path, cardinalitySealJob, want, sealJob)
					}
				}
			}
		})
	}
}

// intsString renders xs as a comma-joined string so two []int slices can be
// compared (and reported on mismatch) without reflect.DeepEqual's less
// readable failure output. Shared with TestPerfProfileShardMatrixCoversEverySlice
// in perf_profile_gate_test.go, which pins the same "declared shard indices
// are the contiguous 1..N sequence" property for the sibling perf-profile
// matrix — both live in this package, so this one definition serves both
// rather than each file growing its own copy of the same idiom.
func intsString(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = strconv.Itoa(x)
	}
	return strings.Join(parts, ",")
}
