package regression

import (
	"strings"
	"testing"
)

// parityLedgerRecipeName regenerates the two parser-surface parity ledgers. It
// is the only thing that repairs them; the `parity` shard must therefore reach
// it.
const parityLedgerRecipeName = "update-parity-ledgers"

// parityLedgerEnv is the switch the recipe's body sets to put both harnesses in
// rewrite mode. A shard that runs a recipe no longer setting it would be running
// a no-op: the same `go test` invocation without it asserts the ledgers instead.
const parityLedgerEnv = "CERBERUS_UPDATE_INVENTORY"

// parityLedgerDirs hold the ledgers the recipe rewrites, and are the paths
// `update-golden`'s closing review diff has to cover.
var parityLedgerDirs = []string{"test/surface-parity", "test/rejection-parity"}

// parityTriggerFile is a parser-surface input: the rejection catalogue records
// every rejection site in internal/{promql,logql,traceql}, so touching one of
// those packages drifts it.
const parityTriggerFile = "internal/traceql/lower.go"

// dockerBackedVerdicts is the third artefact in these directories. It is
// regenerated by a script that probes a live reference Prometheus in a
// container, so it does NOT belong in a recipe a shard invokes — see the
// comment on the assertion below.
const dockerBackedVerdicts = "promql-reference-verdicts.json"

// TestUpdateGoldenChainsParityLedgers pins the reachability that closes #1595.
//
// test/surface-parity/inventory.json records every symbol the three parsers
// expose together with cerberus's in-process verdict for each, and
// test/rejection-parity/catalogue/ records every rejection site in
// internal/{promql,logql,traceql}. Both re-probe the parsers directly, so they
// drift on a parser-surface change — a different trigger from the TXTAR
// goldens, but the identical failure shape #1573 fixed for the migration
// reports: a contributor changes the surface, runs the one recipe every doc
// points at, is told there is zero remaining churn, and meets the drift on a
// CI lane instead.
//
// Sharding #1898 kept the guarantee and made it conditional: the ledgers
// regenerate whenever the caller's shard set includes `parity`, and the coverage
// check demands that shard the moment the branch touches a package the ledgers
// are derived from. Four things have to hold, and this test fails if any one is
// removed:
//
//  1. The `parity` shard reaches `update-parity-ledgers` at all.
//  2. A parser-surface change pulls the shard in — the half that replaces the
//     old unconditional chaining.
//  3. The shard runs BEFORE the fixture body, so its output lands inside the
//     closing diff-stat rather than after it. Nothing pulls the other way: the
//     recipe reads `internal/**`, never `test/spec/**`, so the body's golden
//     rewrite cannot change what it records.
//  4. The closing diff-stat actually covers both ledger directories.
func TestUpdateGoldenChainsParityLedgers(t *testing.T) {
	t.Parallel()

	plan := goldenUpdatePlan(t)

	step := planStepFor(t, plan, parityShard)
	if !strings.Contains(step, parityLedgerRecipeName) {
		t.Errorf("the %q shard runs %q, which does not reach %q. The parity ledgers regenerate "+
			"under no other recipe, so without it a parser-surface change reports zero remaining "+
			"churn locally and still lands red on the lane that verifies them.",
			parityShard, strings.TrimSpace(step), parityLedgerRecipeName)
	}

	out, code := checkGoldenShardCoverage(t, "promql", parityTriggerFile)
	if code == 0 || !strings.Contains(out, "`"+parityShard+"` shard") {
		t.Errorf("changing %s did not demand the %q shard (exit %d). The rejection catalogue "+
			"records every rejection site in that package, so it drifts — and a contributor who "+
			"named only `promql` would be told there is nothing left to regenerate.\n%s",
			parityTriggerFile, parityShard, code, out)
	}

	if got, body := indexOfShard(t, plan, parityShard), planBodyStart(t, plan); got > body {
		t.Errorf("the %q shard runs at plan step %d, after the fixture body starts at step %d. "+
			"Output produced after the body lands outside the closing diff-stat: the drift gets "+
			"repaired but never reaches the diff the contributor is asked to review.\n%s",
			parityShard, got, body, strings.Join(plan, "\n"))
	}

	justfile := readFileString(t, justfilePath)
	parity := justRecipeBody(t, justfile, parityLedgerRecipeName)
	if !strings.Contains(parity, parityLedgerEnv) {
		t.Errorf("%s: the %q recipe no longer sets %s, so it asserts the ledgers instead of "+
			"rewriting them. The %q shard would then be inert — green on an in-sync tree, "+
			"useless on the drift it exists to repair.",
			justfilePath, parityLedgerRecipeName, parityLedgerEnv, parityShard)
	}

	// The recipe must stay pure-local. `promql-reference-verdicts.json` lives in
	// the same directory and is regenerated by a script that starts a reference
	// Prometheus container, which is a heavier prerequisite than `update-golden`
	// assumes — folding it in would make a shard of the one command every doc
	// points at require Docker and a registry pull. Keeping it out is the
	// decision #1595 asked to confirm, so the pin states it rather than leaving
	// the next sweep to re-derive it.
	if strings.Contains(parity, dockerBackedVerdicts) {
		t.Errorf("%s: the %q recipe names %s. That artefact is regenerated against a live "+
			"reference Prometheus in a container, so folding it in would give the %q shard a "+
			"Docker prerequisite it does not have today. It belongs with the k3d/compose "+
			"inventories and the compat parity baseline, outside the shard.",
			justfilePath, parityLedgerRecipeName, dockerBackedVerdicts, parityShard)
	}

	scope := planDiffScope(t, plan)
	for _, dir := range parityLedgerDirs {
		if !strings.Contains(scope, dir) {
			t.Errorf("the closing diff-stat (%q) does not cover %s. Regenerating a ledger and "+
				"then scoping the review prompt so it cannot appear leaves the drift as "+
				"invisible as it was before.", strings.TrimSpace(scope), dir)
		}
	}
}
