package regression

import (
	"strings"
	"testing"
)

const (
	// parityLedgerRecipeName regenerates the two parser-surface parity ledgers.
	parityLedgerRecipeName = "update-parity-ledgers"

	// parityEnrolmentRecipeName regenerates the exact per-head fixture rosters.
	parityEnrolmentRecipeName = "update-parity-enrolment-baseline"
)

// parityLedgerEnv is the switch the recipe's body sets to put both harnesses in
// rewrite mode. A shard that runs a recipe no longer setting it would be running
// a no-op: the same `go test` invocation without it asserts the ledgers instead.
const parityLedgerEnv = "CERBERUS_UPDATE_INVENTORY"

// parityEnrolmentEnv switches the roster assertion into rewrite mode.
const parityEnrolmentEnv = "UPDATE_PARITY_ENROLMENT_BASELINE"

// parityArtifactDirs hold the artefacts the recipe rewrites, and are the paths
// `update-golden`'s closing review diff has to cover.
var parityArtifactDirs = []string{
	"test/surface-parity",
	"test/rejection-parity",
	"test/regression/parity-enrolment-baselines",
}

// parityTriggerFile is a parser-surface input: the rejection catalogue records
// every rejection site in internal/{promql,logql,traceql}, so touching one of
// those packages drifts it.
const parityTriggerFile = "internal/traceql/lower.go"

// parityEnrolmentTriggerFile is fixture input to the exact enrolment roster.
const parityEnrolmentTriggerFile = "test/spec/promql/fixture_under_test.txtar"

// dockerBackedVerdicts is the third artefact in these directories. It is
// regenerated by a script that probes a live reference Prometheus in a
// container, so it does NOT belong in a recipe a shard invokes — see the
// comment on the assertion below.
const dockerBackedVerdicts = "promql-reference-verdicts.json"

// TestUpdateGoldenChainsParityArtifacts pins the complete parity shard graph.
//
// test/surface-parity/inventory.json records every symbol the three parsers
// expose together with cerberus's in-process verdict for each, and
// test/rejection-parity/catalogue/ records every rejection site in
// internal/{promql,logql,traceql}; the enrolment baselines record the exact
// identities of QL fixtures carrying `-- parity --`. The first two drift on a
// parser-surface change and the latter on a fixture change. All three have the
// same failure shape: a contributor runs the canonical generator, is told
// there is zero remaining churn, and meets unreported drift in CI instead.
//
// Sharding #1898 kept the guarantee and made it conditional: the ledgers
// regenerate whenever the caller's shard set includes `parity`, and the coverage
// check demands that shard the moment the branch touches a package the ledgers
// are derived from. Four things have to hold, and this test fails if any one is
// removed:
//
//  1. The `parity` shard reaches both existing generators.
//  2. Parser-surface and QL fixture changes both pull the shard in.
//  3. The shard runs BEFORE the fixture body, so its output lands inside the
//     closing diff-stat rather than after it. The fixture body never rewrites
//     either the parser source or `-- parity --` sections it records.
//  4. The closing diff-stat actually covers all three artefact directories.
func TestUpdateGoldenChainsParityArtifacts(t *testing.T) {
	t.Parallel()

	plan := goldenUpdatePlan(t)

	step := planStepFor(t, plan, parityShard)
	if !strings.Contains(step, parityLedgerRecipeName) {
		t.Errorf("the %q shard runs %q, which does not reach %q.",
			parityShard, strings.TrimSpace(step), parityLedgerRecipeName)
	}

	out, code := checkGoldenShardCoverage(t, "promql", parityTriggerFile)
	if code == 0 || !strings.Contains(out, "`"+parityShard+"` shard") {
		t.Errorf("changing %s did not demand the %q shard (exit %d). The rejection catalogue "+
			"records every rejection site in that package, so it drifts — and a contributor who "+
			"named only `promql` would be told there is nothing left to regenerate.\n%s",
			parityTriggerFile, parityShard, code, out)
	}

	// The negative control that exposed the gap: all other PromQL fixture
	// artefacts are covered, but omitting parity must still be rejected because
	// the exact enrolment roster derives from the fixture itself.
	out, code = checkGoldenShardCoverage(t, "solver promql cardinality", parityEnrolmentTriggerFile)
	if code == 0 || !strings.Contains(out, "`"+parityShard+"` shard") {
		t.Errorf("changing %s did not demand the %q shard (exit %d). The exact parity enrolment "+
			"roster derives from that corpus and would remain stale.\n%s",
			parityEnrolmentTriggerFile, parityShard, code, out)
	}

	if got, body := indexOfShard(t, plan, parityShard), planBodyStart(t, plan); got > body {
		t.Errorf("the %q shard runs at plan step %d, after the fixture body starts at step %d. "+
			"Output produced after the body lands outside the closing diff-stat: the drift gets "+
			"repaired but never reaches the diff the contributor is asked to review.\n%s",
			parityShard, got, body, strings.Join(plan, "\n"))
	}

	justfile := readFileString(t, justfilePath)
	parity := justRecipeBodyWithDeps(t, justfile, parityLedgerRecipeName)
	for _, recipe := range []string{parityLedgerRecipeName, parityEnrolmentRecipeName} {
		if !strings.Contains(parity, recipe+":") {
			t.Errorf("%s: the %q recipe does not reach %q.",
				justfilePath, parityLedgerRecipeName, recipe)
		}
	}
	if !strings.Contains(parity, parityLedgerEnv) {
		t.Errorf("%s: the %q recipe no longer sets %s, so it asserts the ledgers instead of "+
			"rewriting them. The %q shard would then be inert — green on an in-sync tree, "+
			"useless on the drift it exists to repair.",
			justfilePath, parityLedgerRecipeName, parityLedgerEnv, parityShard)
	}
	if !strings.Contains(parity, parityEnrolmentEnv) {
		t.Errorf("%s: the %q recipe no longer sets %s, so it asserts the enrolment baselines "+
			"instead of rewriting them. The %q shard would leave fixture-roster drift stale.",
			justfilePath, parityLedgerRecipeName, parityEnrolmentEnv, parityShard)
	}

	// The recipe must stay pure-local. `promql-reference-verdicts.json` lives in
	// the same directory and is regenerated by a script that starts a reference
	// Prometheus container, which is a heavier prerequisite than `update-golden`
	// assumes — folding it in would make a shard of the one command every doc
	// points at require Docker and a registry pull. Keeping it out is the
	// decision #1595 asked to confirm, so the pin states it rather than leaving
	// the next sweep to re-derive it.
	if strings.Contains(parity, dockerBackedVerdicts) {
		t.Errorf("%s: the %q recipe names %s. That artefact is regenerated against a live "+
			"reference Prometheus in a container, so folding it in would give the %q shard a "+
			"Docker prerequisite it does not have today. It belongs with the k3d/compose "+
			"inventories and the compat parity baseline, outside the shard.",
			justfilePath, parityLedgerRecipeName, dockerBackedVerdicts, parityShard)
	}

	scope := planDiffScope(t, plan)
	for _, dir := range parityArtifactDirs {
		if !strings.Contains(scope, dir) {
			t.Errorf("the closing diff-stat (%q) does not cover %s. Regenerating a ledger and "+
				"then scoping the review prompt so it cannot appear leaves the drift as "+
				"invisible as it was before.", strings.TrimSpace(scope), dir)
		}
	}
}
