package regression

import (
	"strings"
	"testing"
)

// parityLedgerRecipeName regenerates the two parser-surface parity ledgers. It
// is the only thing that repairs them; `update-golden` must therefore reach it.
const parityLedgerRecipeName = "update-parity-ledgers"

// parityLedgerEnv is the switch the recipe's body sets to put both harnesses in
// rewrite mode. Chaining a recipe that no longer sets it would be chaining a
// no-op: the same `go test` invocation without it asserts the ledgers instead.
const parityLedgerEnv = "CERBERUS_UPDATE_INVENTORY"

// parityLedgerDirs hold the ledgers the recipe rewrites, and are the paths
// `update-golden`'s closing review diff has to cover.
var parityLedgerDirs = []string{"test/surface-parity/", "test/rejection-parity/"}

// dockerBackedVerdicts is the third artefact in these directories. It is
// regenerated by a script that probes a live reference Prometheus in a
// container, so it does NOT belong in a recipe `update-golden` chains — see the
// comment on the assertion below.
const dockerBackedVerdicts = "promql-reference-verdicts.json"

// TestUpdateGoldenChainsParityLedgers pins the chaining that closes #1595.
//
// test/surface-parity/inventory.json records every symbol the three parsers
// expose together with cerberus's in-process verdict for each, and
// test/rejection-parity/catalogue/ records every rejection site in
// internal/{promql,logql,traceql}. Both re-probe the parsers directly, so they
// drift on a parser-surface change — a different trigger from the TXTAR
// goldens, but the identical failure shape #1573 fixed for the migration
// reports: a contributor changes the surface, runs the one recipe every doc
// points at, is told there is zero remaining churn, and meets the drift on a
// CI lane instead.
//
// Three things have to hold, and this test fails if any one is removed:
//
//  1. `update-golden` reaches `update-parity-ledgers` at all.
//  2. It reaches it as a PRIOR dependency. `just` runs subsequent (`&&`)
//     dependencies after the body, so a subsequent one would rewrite the
//     ledgers after the closing diff-stat had already printed — repaired but
//     invisible in the diff the contributor is asked to review. Nothing pulls
//     the other way: the recipe reads `internal/**`, never `test/spec/**`, so
//     the body's golden rewrite cannot change what it records.
//  3. The closing diff-stat actually covers both ledger directories.
func TestUpdateGoldenChainsParityLedgers(t *testing.T) {
	t.Parallel()

	justfile := readFileString(t, justfilePath)
	body := justRecipeBody(t, justfile, strings.TrimSuffix(updateGoldenRecipePrefix, ":"))
	header, _, _ := strings.Cut(body, "\n")

	deps := strings.TrimPrefix(header, updateGoldenRecipePrefix)
	prior, subsequent, _ := strings.Cut(deps, subsequentDepSeparator)

	switch {
	case strings.Contains(prior, parityLedgerRecipeName):
		// The pinned shape.
	case strings.Contains(subsequent, parityLedgerRecipeName):
		t.Errorf("%s: %q is a SUBSEQUENT (%q) dependency of %q. `just` runs those after the body, "+
			"so the closing %q has already printed by the time the ledgers are rewritten: the "+
			"drift gets repaired but never reaches the diff the contributor is asked to review. "+
			"Move it to the prior-dependency list.",
			justfilePath, parityLedgerRecipeName, subsequentDepSeparator, updateGoldenRecipePrefix,
			goldenReviewDiffCommand)
	default:
		t.Errorf("%s: %q does not depend on %q (dependencies are %q). The parity ledgers regenerate "+
			"under no other recipe, so without this chaining a parser-surface change reports zero "+
			"remaining churn locally and still lands red on the lane that verifies them. Restore it "+
			"as a prior dependency rather than deleting this pin.",
			justfilePath, updateGoldenRecipePrefix, parityLedgerRecipeName, strings.TrimSpace(deps))
	}

	parity := justRecipeBody(t, justfile, parityLedgerRecipeName)
	if !strings.Contains(parity, parityLedgerEnv) {
		t.Errorf("%s: the %q recipe no longer sets %s, so it asserts the ledgers instead of "+
			"rewriting them. Chaining it into %q would then be inert — green on an in-sync tree, "+
			"useless on the drift it exists to repair.",
			justfilePath, parityLedgerRecipeName, parityLedgerEnv, updateGoldenRecipePrefix)
	}

	// The recipe must stay pure-local. `promql-reference-verdicts.json` lives in
	// the same directory and is regenerated by a script that starts a reference
	// Prometheus container, which is a heavier prerequisite than `update-golden`
	// assumes — chaining it would make the one command every doc points at
	// require Docker and a registry pull. Keeping it out is the decision #1595
	// asked to confirm, so the pin states it rather than leaving the next sweep
	// to re-derive it.
	if strings.Contains(parity, dockerBackedVerdicts) {
		t.Errorf("%s: the %q recipe names %s. That artefact is regenerated against a live reference "+
			"Prometheus in a container, so folding it in would give %q a Docker prerequisite it does "+
			"not have today. It belongs with the k3d/compose inventories and the compat parity "+
			"baseline, outside the chain.",
			justfilePath, parityLedgerRecipeName, dockerBackedVerdicts, updateGoldenRecipePrefix)
	}

	var reviewLine string
	for _, line := range strings.Split(body, "\n")[1:] {
		if strings.Contains(line, goldenReviewDiffCommand) {
			reviewLine = line
		}
	}
	if reviewLine == "" {
		t.Fatalf("%s: %q has no %q line. That closing diff-stat is the built-in review prompt for "+
			"everything the chain regenerated; this pin cannot check its scope without it.",
			justfilePath, updateGoldenRecipePrefix, goldenReviewDiffCommand)
	}
	for _, dir := range parityLedgerDirs {
		if !strings.Contains(reviewLine, dir) {
			t.Errorf("%s: %q's closing diff-stat (%q) does not cover %s. Regenerating a ledger and "+
				"then scoping the review prompt so it cannot appear leaves the drift as invisible as "+
				"it was before the chaining.",
				justfilePath, updateGoldenRecipePrefix, strings.TrimSpace(reviewLine), dir)
		}
	}
}
