package main

import "text/template"

// docTemplate is the document skeleton: a hand-written, code-reviewed preamble
// and footer wrapping the GENERATED per-group tables. Everything between the
// preamble and the footer is rendered from config.EnvDocs + config.DocDefaults,
// so the env-var tables cannot drift; the prose around them (config-file
// resolution, the cross-setting dependency matrix, the schema preflight
// narrative) is preserved here verbatim because it documents behaviour, not a
// single knob's default.
//
// GENERATED-FILE banner: the output carries an explicit "do not edit" notice so
// a human who opens docs/configuration.md is told to edit this template + the
// metadata instead, and the CI drift gate catches a hand-edit regardless.
var docTemplate = template.Must(template.New("configuration.md").Parse(docTemplateText))

const docTemplateText = `<!-- Code-generated by cmd/config-docs from internal/config metadata + the
     live viper loader defaults. DO NOT EDIT this file by hand: edit the
     EnvDoc metadata in internal/config/envdocs.go (or the preamble/footer in
     cmd/config-docs/template.go) and run "just gen-config-docs". CI gates on
     drift, so a hand-edit will fail the build. -->

# Configuration

Cerberus is a stateless 12-factor binary configured primarily through
` + "`CERBERUS_*`" + ` environment variables. An optional ` + "`cerberus.yaml`" + `
([below](#configuration-file-optional)) may supply file-level defaults, but the
environment contract always wins - env vars are the source of truth.
ClickHouse and the (optional) OpenTelemetry collector are attached resources
reached through env-var connection inputs, so swapping a local single-node
ClickHouse for a managed cluster, or a sidecar collector for a SaaS ingest URL,
is a matter of flipping env vars and restarting. Every default below is the
value ` + "`internal/config/config.go`" + ` ships out of the box, read live from
the viper loader at generation time.

All boolean knobs accept ` + "`1`/`0`/`true`/`false`" + `, case-insensitive (the full
` + "`strconv.ParseBool`" + ` vocabulary), via one shared parser - so ` + "`true`" + ` and ` + "`1`" + ` are
interchangeable for any ` + "`bool`" + `-typed variable below.

Misconfigured values fail fast: an unparseable duration, an out-of-range
integer, an unknown log level, or a malformed OTLP header list aborts startup
with a clear error rather than silently downgrading behaviour. Secrets (the
ClickHouse password, OTLP bearer tokens) live in this same env-var namespace
and are sourced from a Kubernetes ` + "`Secret`" + `, a Docker ` + "`secrets:`" + ` mount, or a
vault-injecting init container - never committed.

For how these knobs interact with the running service - lifecycle, readiness,
deployment, scaling - see [` + "`operations.md`" + `](operations.md).

## Configuration file (optional)

Cerberus loads configuration through a [viper](https://github.com/spf13/viper)
loader, so an **optional** ` + "`cerberus.yaml`" + ` may supply values alongside the
environment. The resolution order is:

1. **Environment variable** (` + "`CERBERUS_*`" + `) - always wins.
2. **Config file** (` + "`cerberus.yaml`" + `) - fills in anything the environment leaves
   unset.
3. **Built-in default** - the value ` + "`internal/config/config.go`" + ` ships.

The loader probes two paths for ` + "`cerberus.yaml`" + `, in order: the **working
directory** (` + "`.`" + `) and **` + "`/etc/cerberus`" + `**. The file is **purely additive** - it
can only supply a value the operator hasn't set in the environment; it can never
override an env var. That keeps the 12-factor contract intact (the deployment's
environment remains the source of truth) while giving a baked-image or
bare-metal deployment a place to pin defaults without a long ` + "`-e`" + ` list.

The file is **optional and best-effort**: a **missing** ` + "`cerberus.yaml`" + ` is not
an error, and a **malformed** one is tolerated at load time rather than crashing
startup - values still resolve from the environment and the built-in defaults.
Each resolved value, whatever its source, is then run through the **same
fail-fast typed validation** an env value gets: an unparseable duration or an
out-of-range integer supplied by the file aborts startup with the same clear
error it would from an env var.

The keys are the literal ` + "`CERBERUS_*`" + ` names (the loader binds each viper key to
its environment variable). A minimal example pinning the ClickHouse endpoint and
log format:

` + "```yaml" + `
# /etc/cerberus/cerberus.yaml - defaults; any CERBERUS_* env var overrides these
CERBERUS_CH_ADDR: clickhouse.observability.svc:9000
CERBERUS_CH_DATABASE: otel
CERBERUS_LOG_FORMAT: json
CERBERUS_ADMIT_TEMPO: 24
` + "```" + `

Secrets (the ClickHouse password, OTLP bearer tokens) are best left **out** of
the file and injected through the environment from a Kubernetes ` + "`Secret`" + ` or a
vault sidecar, exactly as without a config file - the file is for non-secret
defaults.
{{ range .Sections }}
## {{ .Name }}
{{ if .Intro }}
{{ .Intro }}
{{ end }}
{{ .Table }}
{{ end }}
## Schema overrides and Prometheus resource labels

Two further env-var families shape ClickHouse interaction but are resolved by
` + "`internal/schema`" + ` (not the loader documented above), so they carry no built-in
viper default and are documented in
[` + "`observability.md`" + `](observability.md#schema-shape-overrides):

- **Schema-shape table-name overrides** - ` + "`CERBERUS_SCHEMA_METRICS_*_TABLE`" + `,
  ` + "`CERBERUS_SCHEMA_LOGS_TABLE`" + `, ` + "`CERBERUS_SCHEMA_TRACES_TABLE`" + ` - the table
  names cerberus reads when the ClickHouse layout deviates from the OTel-CH
  exporter defaults. The auto-create hook creates and the query heads read the
  same names, so a rename is consistent end to end.
- **` + "`CERBERUS_PROM_RESOURCE_LABELS`" + `** - allowlist of OTel ` + "`ResourceAttributes`" + `
  keys (dotted form, e.g. ` + "`k8s.namespace.name`" + `) projected as Prometheus labels.
  Empty / unset promotes **every** resource key.

The solver-tuning surface (` + "`CERBERUS_EVAL_ROUTE`" + `, ` + "`CERBERUS_SHARD_*`" + `,
` + "`CERBERUS_SOLVER_TIMEOUT`" + `) is likewise resolved by ` + "`internal/solver`" + ` and is
documented in [` + "`solver.md`" + `](solver.md).

## Dependency matrix

Most knobs are validated in isolation (unknown enum, out-of-range buffer,
malformed URL, non-positive where positive is required). Some knobs, however,
only make sense in combination - an individually-valid value can be incoherent
next to another. Cerberus rejects these **combinations** at startup with an
error that names both knobs, rather than silently ignoring or downgrading one
of them. The full set of cross-setting rules:

{{ .DependencyMatrix }}

Benign-but-pointless combinations are **not** hard errors - they are noted here
rather than rejected:

- ` + "`CERBERUS_CH_CONN_OPEN_STRATEGY=round_robin`" + ` with a single ` + "`CERBERUS_CH_ADDR`" + `
  host: the strategy has nothing to rotate over, but it is harmless.
- Keepalive timing sub-knobs (` + "`CERBERUS_CH_KEEPALIVE_IDLE`" + ` / ` + "`_INTERVAL`" + ` /
  ` + "`_COUNT`" + `) while ` + "`CERBERUS_CH_KEEPALIVE_ENABLED=false`" + `: inert (the kernel never
  arms a probe schedule), so a degenerate value is accepted, not rejected.
`
