package surfaceparity

import (
	"encoding/json"
	"fmt"
	"os"
)

// logqlReferenceVerdictsPath is the checked-in artifact recording the
// reference Loki verdict per LogQL Op* symbol.
const logqlReferenceVerdictsPath = "logql-reference-verdicts.json"

// logqlReferenceVerdicts is the parsed reference-verdict ledger.
//
// The artifact is generated by logql_reference_agpl_test.go (an
// agpl_oracle-tagged regeneration test — see that file's doc comment)
// re-running the SAME domain-aware probe this package synthesizes for
// every entry in logProbes through the reference's in-process
// lsyntax.ParseExpr (parse + validate). That call is data-independent
// (parse + type validation only), so the artifact is a pure function of
// logProbes, not of any fixture or live service.
//
// This mirrors promql_reference.go's pinned-artifact pattern: reading a
// frozen verdict here keeps this package (and the default `check` gate
// that exercises it via TestInventoryIsRegenerable) free of the AGPL
// grafana/loki import that computing the verdict live would require.
// See #1520.
type logqlReferenceVerdicts struct {
	Verdicts map[string]string `json:"verdicts"`
}

// loadLogQLReferenceVerdicts reads + parses the pinned artifact.
func loadLogQLReferenceVerdicts() (*logqlReferenceVerdicts, error) {
	raw, err := os.ReadFile(logqlReferenceVerdictsPath) //nolint:gosec // repo-relative artifact path
	if err != nil {
		return nil, fmt.Errorf("read %s (regenerate via 'go test -tags agpl_oracle -run TestLogQLReferenceVerdictsAreCurrent ./test/surface-parity/'): %w", logqlReferenceVerdictsPath, err)
	}
	return parseLogQLReferenceVerdicts(raw)
}

// parseLogQLReferenceVerdicts decodes + validates the artifact bytes,
// split out from loadLogQLReferenceVerdicts so the malformed-JSON and
// empty-verdicts error paths are unit-testable without touching the
// filesystem.
func parseLogQLReferenceVerdicts(raw []byte) (*logqlReferenceVerdicts, error) {
	var rv logqlReferenceVerdicts
	if err := json.Unmarshal(raw, &rv); err != nil {
		return nil, fmt.Errorf("parse %s: %w", logqlReferenceVerdictsPath, err)
	}
	if len(rv.Verdicts) == 0 {
		return nil, fmt.Errorf("%s has no verdicts", logqlReferenceVerdictsPath)
	}
	return &rv, nil
}

// verdict returns the reference verdict for a logProbes symbol. A
// symbol present in logProbes but MISSING from the artifact is a hard
// error, not a silent accept: the artifact must cover the full probe
// set, so a gap means a probe was added without regenerating the
// artifact — exactly the case the surface-completeness gate exists to
// catch.
func (rv *logqlReferenceVerdicts) verdict(symbol string) (Verdict, error) {
	v, ok := rv.Verdicts[symbol]
	if !ok {
		return "", fmt.Errorf("%s: no reference verdict for %q — logProbes grew a symbol the pinned artifact "+
			"doesn't cover; regenerate via 'go test -tags agpl_oracle -run TestLogQLReferenceVerdictsAreCurrent ./test/surface-parity/'",
			logqlReferenceVerdictsPath, symbol)
	}
	switch Verdict(v) {
	case VerdictAccept:
		return VerdictAccept, nil
	case VerdictReject:
		return VerdictReject, nil
	default:
		return "", fmt.Errorf("%s: symbol %q has invalid verdict %q (want accept/reject)", logqlReferenceVerdictsPath, symbol, v)
	}
}
