package surfaceparity

import (
	"encoding/json"
	"fmt"
	"os"
)

// referenceVerdictsPath is the checked-in artifact recording the
// flag-enabled reference Prometheus verdict per PromQL parser symbol.
const referenceVerdictsPath = "promql-reference-verdicts.json"

// referenceVerdicts is the parsed flag-enabled-reference verdict ledger.
//
// The artifact is generated by .github/scripts/promql-surface-gate.mjs in
// regenerate mode: it stands up prom/prometheus:v3.11.3 with
// --enable-feature=promql-experimental-functions, drives the SAME
// domain-aware probe this package synthesizes for every parser.Functions
// symbol + the two experimental aggregators through the reference's
// HTTP /api/v1/query endpoint, and records the runtime verdict
// (2xx => accept, 4xx => reject). The verdict is parse + type validation,
// which is data-independent: a well-typed accepted expression returns 2xx
// even with no series seeded, and a parse/type error returns 4xx — so the
// artifact is a pure function of the reference's grammar surface under the
// experimental-functions flag, not of any fixture.
//
// This REPLACES the former `if fn.Experimental { ref = reject }` oracle
// stand-in (promql.go), which modelled a flag-OFF reference and therefore
// mislabelled every flag-ON-implemented experimental fn. See
// referenceVerdictPromQL's call-site comment for the bug it closes.
//
// The CI gate (.github/scripts/promql-surface-gate.mjs) re-probes the live
// reference on every run and fails if the live verdict drifts from this
// pinned artifact, so the in-process ratchet (which reads the artifact,
// Docker-free, in `just test`) can never silently diverge from the real
// reference.
type referenceVerdicts struct {
	Verdicts map[string]string `json:"verdicts"`
}

// loadReferenceVerdicts reads + parses the pinned artifact.
func loadReferenceVerdicts() (*referenceVerdicts, error) {
	raw, err := os.ReadFile(referenceVerdictsPath) //nolint:gosec // repo-relative artifact path
	if err != nil {
		return nil, fmt.Errorf("read %s (regenerate via .github/scripts/promql-surface-gate.mjs): %w", referenceVerdictsPath, err)
	}
	var rv referenceVerdicts
	if err := json.Unmarshal(raw, &rv); err != nil {
		return nil, fmt.Errorf("parse %s: %w", referenceVerdictsPath, err)
	}
	if len(rv.Verdicts) == 0 {
		return nil, fmt.Errorf("%s has no verdicts", referenceVerdictsPath)
	}
	return &rv, nil
}

// verdict returns the flag-enabled reference verdict for a symbol key
// ("fn:<name>" / "agg:<op>"). A symbol present in parser.Functions but
// MISSING from the artifact is a hard error, not a silent accept: the
// artifact must cover the full pinned parser surface, so a gap means the
// artifact is stale relative to a fork bump that added a symbol — exactly
// the case the surface-completeness gate exists to catch. The fix is to
// regenerate the artifact against the flag-enabled reference, never to
// default the missing symbol to a verdict.
func (rv *referenceVerdicts) verdict(symbol string) (Verdict, error) {
	v, ok := rv.Verdicts[symbol]
	if !ok {
		return "", fmt.Errorf("%s: no reference verdict for %q — the pinned parser surface grew a symbol the "+
			"flag-enabled-reference artifact doesn't cover; regenerate via .github/scripts/promql-surface-gate.mjs",
			referenceVerdictsPath, symbol)
	}
	switch Verdict(v) {
	case VerdictAccept:
		return VerdictAccept, nil
	case VerdictReject:
		return VerdictReject, nil
	default:
		return "", fmt.Errorf("%s: symbol %q has invalid verdict %q (want accept/reject)", referenceVerdictsPath, symbol, v)
	}
}
