package surfaceparity

import (
	"encoding/json"
	"fmt"
	"os"
)

// traceqlReferenceVerdictsPath is the checked-in artifact recording the
// reference Tempo verdict per TraceQL intrinsic/metrics-op/aggregate
// symbol.
const traceqlReferenceVerdictsPath = "traceql-reference-verdicts.json"

// traceqlReferenceVerdicts is the parsed reference-verdict ledger.
//
// The artifact is generated by traceql_reference_agpl_test.go (an
// agpl_oracle-tagged regeneration test — see that file's doc comment)
// re-running the SAME domain-aware probe this package synthesizes for
// every intrinsic/metrics-op/aggregate probe through the reference's
// in-process tempotraceql.Parse + tempotraceql.Validate (parse + the
// unsupported-feature gate). That call is data-independent, so the
// artifact is a pure function of the probe tables, not of any fixture
// or live service.
//
// This mirrors promql_reference.go's / logql_reference.go's
// pinned-artifact pattern: reading a frozen verdict here keeps this
// package (and the default `check` gate that exercises it via
// TestInventoryIsRegenerable) free of the AGPL grafana/tempo import
// that computing the verdict live would require. See #1520.
type traceqlReferenceVerdicts struct {
	Verdicts map[string]string `json:"verdicts"`
}

// loadTraceQLReferenceVerdicts reads + parses the pinned artifact.
func loadTraceQLReferenceVerdicts() (*traceqlReferenceVerdicts, error) {
	raw, err := os.ReadFile(traceqlReferenceVerdictsPath) //nolint:gosec // repo-relative artifact path
	if err != nil {
		return nil, fmt.Errorf("read %s (regenerate via 'go test -tags agpl_oracle -run TestTraceQLReferenceVerdictsAreCurrent ./test/surface-parity/'): %w", traceqlReferenceVerdictsPath, err)
	}
	var rv traceqlReferenceVerdicts
	if err := json.Unmarshal(raw, &rv); err != nil {
		return nil, fmt.Errorf("parse %s: %w", traceqlReferenceVerdictsPath, err)
	}
	if len(rv.Verdicts) == 0 {
		return nil, fmt.Errorf("%s has no verdicts", traceqlReferenceVerdictsPath)
	}
	return &rv, nil
}

// verdict returns the reference verdict for a probe symbol (from
// tqlIntrinsicProbes / tqlMetricsProbes / tqlAggregateProbes). A symbol
// present in the probe tables but MISSING from the artifact is a hard
// error, not a silent accept: the artifact must cover the full probe
// set, so a gap means a probe was added without regenerating the
// artifact — exactly the case the surface-completeness gate exists to
// catch.
func (rv *traceqlReferenceVerdicts) verdict(symbol string) (Verdict, error) {
	v, ok := rv.Verdicts[symbol]
	if !ok {
		return "", fmt.Errorf("%s: no reference verdict for %q — the probe tables grew a symbol the pinned artifact "+
			"doesn't cover; regenerate via 'go test -tags agpl_oracle -run TestTraceQLReferenceVerdictsAreCurrent ./test/surface-parity/'",
			traceqlReferenceVerdictsPath, symbol)
	}
	switch Verdict(v) {
	case VerdictAccept:
		return VerdictAccept, nil
	case VerdictReject:
		return VerdictReject, nil
	default:
		return "", fmt.Errorf("%s: symbol %q has invalid verdict %q (want accept/reject)", traceqlReferenceVerdictsPath, symbol, v)
	}
}
