{{- if and .Values.clickhouse.bundled.enabled .Values.clickhouse.bundled.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cerberus.clickhouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cerberus.clickhouse.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.clickhouse.bundled.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cerberus.clickhouse.selectorLabels" . | nindent 6 }}
{{- end }}
