{{- if and .Values.clickhouse.bundled.enabled .Values.clickhouse.bundled.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cerberus.clickhouse.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cerberus.clickhouse.labels" . | nindent 4 }}
  {{- with .Values.clickhouse.bundled.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
