//go:build chdb

package main

import (
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/tsouza/cerberus/internal/solver"
)

type docInput struct {
	wins    []headlineWin
	curves  []scalingCurve
	sharded shardedResult
	e2e     []e2eResult
	matrix  matrixResult
	micro   []microResult

	iters     int
	benchtime string

	metricRows, logRows, traceRows int64

	goVersion string
	goarch    string
	goos      string
	numCPU    int
	host      hostInfo

	// outPath is where benchmarks.md is written; charts are emitted into a
	// sibling benchmarks/ directory and referenced relative to it.
	outPath string
}

// align enumerates a markdown table column's alignment for the separator
// row and cell padding.
type align int

const (
	alignLeft align = iota
	alignRight
)

// writeTable emits a markdownlint-MD060-compliant aligned table: every
// pipe lines up because each cell is padded to its column's max width.
// aligns gives the per-column alignment (left/right); header + rows must
// all have len(aligns) cells.
func writeTable(b *strings.Builder, aligns []align, header []string, rows [][]string) {
	widths := make([]int, len(aligns))
	for i, h := range header {
		widths[i] = utf8.RuneCountInString(h)
	}
	for _, r := range rows {
		for i, c := range r {
			if w := utf8.RuneCountInString(c); w > widths[i] {
				widths[i] = w
			}
		}
	}
	// The separator cell is `---`/`---:`; ensure the column is wide enough
	// for it (min 3, +1 for the right-align colon).
	for i, a := range aligns {
		minW := 3
		if a == alignRight {
			minW = 4
		}
		if widths[i] < minW {
			widths[i] = minW
		}
	}

	writeRow := func(cells []string) {
		b.WriteString("|")
		for i, c := range cells {
			pad := widths[i] - utf8.RuneCountInString(c)
			if aligns[i] == alignRight {
				b.WriteString(" " + strings.Repeat(" ", pad) + c + " |")
			} else {
				b.WriteString(" " + c + strings.Repeat(" ", pad) + " |")
			}
		}
		b.WriteString("\n")
	}
	writeRow(header)
	// separator
	b.WriteString("|")
	for i, a := range aligns {
		if a == alignRight {
			b.WriteString(" " + strings.Repeat("-", widths[i]-1) + ": |")
		} else {
			b.WriteString(" " + strings.Repeat("-", widths[i]) + " |")
		}
	}
	b.WriteString("\n")
	for _, r := range rows {
		writeRow(r)
	}
}

// renderDoc assembles the full benchmarks.md, written to read top-to-bottom
// like a story: what we measure → where → how → the end-to-end numbers →
// the rate-range strategy table → scaling → the per-component micro costs →
// how to reproduce. Charts are emitted as committed SVGs alongside the doc
// and referenced inline. Timings are rounded to keep regenerated diffs
// small; deterministic ratios carry one decimal.
func renderDoc(in docInput) (string, error) {
	var b strings.Builder

	renderIntro(&b, in)
	renderEnvironment(&b, in)
	renderMethodology(&b, in)
	if err := renderE2E(&b, in); err != nil {
		return "", err
	}
	if err := renderMatrix(&b, in); err != nil {
		return "", err
	}
	renderSharded(&b, in)
	if err := renderScaling(&b, in); err != nil {
		return "", err
	}
	renderHeadlines(&b, in)
	renderMicro(&b, in)
	renderReproducing(&b)
	renderSeeAlso(&b)

	return b.String(), nil
}

// renderIntro — what these benchmarks measure, and what they don't.
func renderIntro(b *strings.Builder, in docInput) {
	b.WriteString("# Cerberus benchmarks\n\n")
	b.WriteString("Cerberus turns a Prometheus / Loki / Tempo query into ClickHouse SQL, runs it, ")
	b.WriteString("and streams the result back in the upstream wire format. This document measures ")
	b.WriteString("**how fast that pipeline is and how much memory it costs** — end to end, for the ")
	b.WriteString("query shapes a real dashboard sends.\n\n")

	b.WriteString("**The one-sentence headline:** on a realistic 500k-row dataset every common ")
	b.WriteString("query returns in tens of milliseconds, and the one genuinely expensive shape — ")
	b.WriteString("a `rate(…)` range query — is exactly the shape cerberus has two complementary ")
	b.WriteString("tools for: the **native `timeSeriesRateToGrid` lowering**, which removes the ")
	b.WriteString("row fan-out entirely, and the **sharded solver**, which keeps the fan-out under ")
	b.WriteString("a per-query memory cap.\n\n")

	b.WriteString("**What this is.** A latency-and-memory profile of the query pipeline: parse → ")
	b.WriteString("lower → optimize → emit SQL → execute → format. **What this is not.** A load ")
	b.WriteString("test. There is no concurrency, no network, no ingest path here — every number ")
	b.WriteString("is the cost of *one* query running *alone* against an embedded ClickHouse ")
	b.WriteString("engine. That makes the numbers stable and comparable; it also means they are a ")
	b.WriteString("floor, not a throughput figure.\n\n")

	b.WriteString("Every number below is **measured**, not estimated, and the whole document is ")
	b.WriteString("regenerated by a single command — see [Reproducing](#reproducing).\n\n")
}

// renderEnvironment — the substrate the numbers come from, with the caveat.
func renderEnvironment(b *strings.Builder, in docInput) {
	b.WriteString("## Environment\n\n")
	b.WriteString("All measurements run **in-process** against an embedded ClickHouse engine ")
	b.WriteString("([chDB](https://github.com/chdb-io/chdb), the ClickHouse engine compiled as a ")
	b.WriteString("library) — no server, no socket, no Docker. The engine is the real ClickHouse ")
	b.WriteString("query executor, so the SQL cerberus emits runs exactly as it would against a ")
	b.WriteString("standalone ClickHouse.\n\n")

	b.WriteString("These numbers were captured on the host below — read directly from ")
	b.WriteString("`/proc` and `/sys` at generation time, so the spec stays accurate and ")
	b.WriteString("regenerates with the rest of the document.\n\n")

	rows := environmentRows(in)
	writeTable(b, []align{alignLeft, alignLeft}, []string{"component", "value"}, rows)
	b.WriteString("\n")

	b.WriteString("> **Your numbers will differ.** Absolute timings depend on the CPU, the Go ")
	b.WriteString("build, and the machine's load at the time. Treat the millisecond figures as ")
	b.WriteString("*order-of-magnitude*; the **ratios** between shapes (and the deterministic ")
	b.WriteString("row / granule counts) are what carry across hardware. Regenerate on your own ")
	b.WriteString("box with `just bench-report`.\n\n")
}

// environmentRows builds the Environment spec table top to bottom: CPU
// identity → core/thread topology → clock → cache hierarchy → memory → OS /
// kernel → Go runtime → query engine. Every host-derived row is gated on a
// non-empty captured value, so a thinner /proc simply yields a shorter table
// rather than rows reading "unknown".
func environmentRows(in docInput) [][]string {
	var rows [][]string
	add := func(component, value string) {
		if value != "" {
			rows = append(rows, []string{component, value})
		}
	}
	h := in.host

	// CPU identity.
	add("CPU", h.cpuModel)
	add("CPU vendor", h.cpuVendor)
	add("CPU family", h.cpuFamily)

	// Topology: cores / threads (/ sockets when more than one).
	if h.cores > 0 && h.threads > 0 {
		topo := fmt.Sprintf("%d physical cores / %d logical threads", h.cores, h.threads)
		if h.sockets > 1 {
			topo += fmt.Sprintf(" across %d sockets", h.sockets)
		}
		add("CPU topology", topo)
	}
	add("Max clock", h.maxMHz)

	// Cache hierarchy as one compact row: "L1d 32 KiB ×4, L2 256 KiB ×4, L3 8 MiB ×1".
	if len(h.caches) > 0 {
		parts := make([]string, 0, len(h.caches))
		for _, c := range h.caches {
			parts = append(parts, fmt.Sprintf("%s %s ×%d", c.label, c.size, c.instances))
		}
		add("CPU cache", strings.Join(parts, ", "))
	}

	add("Memory", h.memTotal)
	add("OS", h.osPretty)
	add("Kernel", h.kernel)

	// Go runtime: version + GOOS/GOARCH + logical CPUs the runtime sees.
	rows = append(rows, []string{"Go toolchain", in.goVersion})
	platform := in.goarch
	if in.goos != "" {
		platform = in.goos + "/" + in.goarch
	}
	rows = append(rows, []string{"Go platform", platform})
	rows = append(rows, []string{"runtime.NumCPU", fmt.Sprintf("%d", in.numCPU)})

	// The query engine the SQL actually executes on.
	rows = append(rows, []string{"Query engine", "ClickHouse 25.8 (via chDB / chdb-go, in-process)"})

	return rows
}

// renderMethodology — the how, explained from first principles.
func renderMethodology(b *strings.Builder, in docInput) {
	b.WriteString("## Methodology\n\n")

	b.WriteString("**Why an in-process engine.** Running ClickHouse as a library removes the two ")
	b.WriteString("biggest sources of noise — network round-trips and a separately-scheduled ")
	b.WriteString("server process. What's left is the cost of the query itself, which is what we ")
	b.WriteString("want to measure. It also makes the whole suite reproducible from one `go run` ")
	b.WriteString("with no infrastructure to stand up.\n\n")

	b.WriteString("**Two kinds of measurement.**\n\n")
	b.WriteString("- **End-to-end** numbers drive a real query the whole way through cerberus's ")
	b.WriteString("production pipeline and execute the emitted SQL on chDB. They answer *\"how long ")
	b.WriteString("does this query take?\"*\n")
	b.WriteString("- **Micro-benchmarks** isolate one Go stage (lowering, the optimizer, SQL ")
	b.WriteString("emission) with `go test -bench`, with no database involved. They answer *\"how ")
	b.WriteString("much does this one stage cost?\"* and catch per-stage allocation regressions.\n\n")

	b.WriteString("**What a \"wall\" number means.** The wall time is the time to execute the ")
	b.WriteString("emitted SQL on chDB, taken as the **best of ")
	fmt.Fprintf(b, "%d** runs. The fastest run is the cleanest estimate — it is the one least ", in.iters)
	b.WriteString("perturbed by GC pauses and OS scheduling, so the floor is the most stable ")
	b.WriteString("single-process signal. Micro-benchmarks use `-benchtime ")
	fmt.Fprintf(b, "%s`.\n\n", in.benchtime)

	b.WriteString("**What a \"peak memory\" number means.** chDB does not expose a per-query ")
	b.WriteString("peak-memory metric and never enforces a memory cap, so peak memory is ")
	b.WriteString("**modeled**, not measured directly: we count the intermediate rows a query ")
	b.WriteString("materializes (the deterministic driver of memory) and scale that by a single ")
	b.WriteString("published calibration constant. Wherever a memory figure appears it is ")
	b.WriteString("labelled *modeled*; the **row count** it derives from is always measured.\n\n")

	fmt.Fprintf(b, "**The dataset: ~500k datapoints.** The end-to-end queries run over a "+
		"synthetic OpenTelemetry dataset of **%s** metric samples, **%s** log records, and "+
		"**%s** spans, generated server-side via `numbers(N)` (no row-by-row inserts). Half a "+
		"million datapoints per signal is the realistic scale of a busy dashboard panel — big "+
		"enough that scan cost and fan-out are visible, small enough that the numbers reflect "+
		"normal operation rather than a pathological stress artifact.\n\n",
		fmtInt(in.metricRows), fmtInt(in.logRows), fmtInt(in.traceRows))

	b.WriteString("**Determinism.** Structural metrics — intermediate row counts, granules read, ")
	b.WriteString("`allocs/op` — are deterministic and committed verbatim, so a regenerated ")
	b.WriteString("document diffs cleanly on them. Timings (`ns/op`, wall, latency) are ")
	b.WriteString("machine-dependent and presented as ratios wherever a before/after exists. This ")
	b.WriteString("document is a **manually-regenerated artifact, not a CI gate** — no test fails ")
	b.WriteString("on timing drift. Structural regressions are guarded separately by the ")
	b.WriteString("cardinality ratchet (`test/perf/cardinality_ratchet_test.go`) and the scaling ")
	b.WriteString("harness (`test/perf/scaling/`).\n\n")
}

// renderE2E leads with the headline e2e table + bar chart.
func renderE2E(b *strings.Builder, in docInput) error {
	b.WriteString("## End-to-end: the `query_range` path\n\n")

	b.WriteString("This is the section to read first. Each query below is driven through the ")
	b.WriteString("**entire production pipeline** — the exact sequence `internal/engine` runs for ")
	b.WriteString("a live request:\n\n")
	b.WriteString("```text\n")
	b.WriteString("parse the query  →  lower to the plan IR  →  optimize (optimizer.Default)\n")
	b.WriteString("  →  emit ClickHouse SQL  →  execute on chDB  →  shape the wire response\n")
	b.WriteString("```\n\n")
	b.WriteString("Nothing is stubbed: the SQL measured is the SQL cerberus emits, and it runs on ")
	b.WriteString("the same 500k-row dataset described above. The query shapes span all three ")
	b.WriteString("heads and the API endpoints a Grafana dashboard actually hits — an instant ")
	b.WriteString("evaluation, a **`query_range`** rate over a step grid (the workhorse panel ")
	b.WriteString("query), a `/series` label lookup, a TraceQL span search, and a LogQL range ")
	b.WriteString("count.\n\n")

	var rows [][]string
	var labels []string
	var vals []float64
	for _, r := range in.e2e {
		rows = append(rows, []string{r.Name, r.Head, fmtInt(r.ScanRows), roundDur(r.Wall)})
		labels = append(labels, e2eShortLabel(r.Name))
		vals = append(vals, float64(r.Wall)/float64(time.Millisecond))
	}
	writeTable(b, []align{alignLeft, alignLeft, alignRight, alignRight},
		[]string{"query", "head", "scan rows", "latency"}, rows)
	b.WriteString("\n")

	ref, err := writeChart(in.outPath, "e2e-latency.svg",
		barChart("End-to-end latency by query shape (500k rows)", "latency (ms)",
			labels, vals, func(v float64) string { return fmtMs(v) }))
	if err != nil {
		return err
	}
	fmt.Fprintf(b, "![End-to-end latency by query shape](%s)\n\n", ref)

	b.WriteString("Query shapes:\n\n")
	for _, r := range in.e2e {
		fmt.Fprintf(b, "- **%s** (`%s`): `%s`\n", r.Name, r.Head, r.Query)
	}
	b.WriteString("\n")

	b.WriteString("Four of the five shapes land in the tens of milliseconds. The outlier is the ")
	b.WriteString("**rate range query** — and that is not an accident of this benchmark but the ")
	b.WriteString("inherent shape of the problem: a `rate(…[5m])` evaluated across a 1-hour grid ")
	b.WriteString("at a 15-second step has to consider, for every step, the samples in its ")
	b.WriteString("trailing 5-minute window. That overlap is a genuine fan-out, and it is the ")
	b.WriteString("subject of the next section.\n\n")
	return nil
}

// renderMatrix — the rate-range strategy table, the centrepiece.
func renderMatrix(b *strings.Builder, in docInput) error {
	m := in.matrix
	b.WriteString("## The expensive shape: rate-range query — three strategies\n\n")

	b.WriteString("The rate range query is where cerberus's two performance levers come into ")
	b.WriteString("play. They are **not independent dials** — they are two *alternative* remedies ")
	b.WriteString("for the same row fan-out:\n\n")
	b.WriteString("- **Sharding** (the [sharded-pushdown solver](solver.md), route B) makes the ")
	b.WriteString("fan-out *fit*. It re-anchors the *same* plan onto **K disjoint anchor-grid ")
	b.WriteString("shards**, each a separate statement over a slice of the grid; no shard sees ")
	b.WriteString("more than ~1/K of the fan-out, so each one stays under the per-query memory ")
	b.WriteString("cap.\n")
	b.WriteString("- **Native rate** (`CERBERUS_EXPERIMENTAL_TS_GRID_RANGE`) makes the fan-out ")
	b.WriteString("*vanish*. ClickHouse's native `timeSeriesRateToGrid` aggregate computes every ")
	b.WriteString("grid point's rate in a single pass with **no row fan-out at all** — it never ")
	b.WriteString("builds the `(sample, anchor)` matrix. It needs ClickHouse ≥ 25.6 (the ")
	b.WriteString("substrate here is 25.8).\n\n")

	b.WriteString("Because native rate *removes* the fan-out, the two levers do not stack: with ")
	b.WriteString("native rate on there is no fan-out spine left for the sharded solver to slice, ")
	b.WriteString("so any route collapses to a single statement. That leaves exactly **three ")
	b.WriteString("genuinely distinct strategies** for this query, not a route × native-rate ")
	b.WriteString("grid.\n\n")

	fmt.Fprintf(b, "**The focus query** is the same rate range query_range from the table above — "+
		"`%s` over %s at a %s step (fan-out F = Range/Step = **%d**, grid N = **%d** steps), on "+
		"the **%s**-row metrics seed. Each strategy drives the full pipeline for its "+
		"configuration and reports two numbers: the measured **wall** time and the modeled "+
		"per-statement **peak memory**.\n\n",
		m.Query, fmtGridDur(m.OuterRange), fmtGridDur(m.Step), m.F, m.N, fmtInt(m.ScanRows))

	// Three-strategy wall + memory table.
	rows := matrixRows(m)
	writeTable(b, []align{alignLeft, alignRight, alignRight, alignRight, alignLeft},
		[]string{"strategy", "statements", "wall", "peak mem", "note"}, rows)
	b.WriteString("\n")

	b.WriteString("`auto` (the production default) picks the sharded route for this query when ")
	b.WriteString("native rate is off; with native rate on it collapses to a single statement — ")
	b.WriteString("so `auto` does not earn its own row, it lands on one of the three above ")
	b.WriteString("depending on the flag.\n\n")

	// One bar per strategy: wall, then peak memory.
	labels, wallVals, memVals := matrixChartData(m)
	wref, err := writeChart(in.outPath, "matrix-wall.svg",
		barChart("Rate range query: wall by strategy", "wall (ms)",
			labels, wallVals, func(v float64) string { return fmtMs(v) }))
	if err != nil {
		return err
	}
	fmt.Fprintf(b, "![Wall by strategy](%s)\n\n", wref)

	mref, err := writeChart(in.outPath, "matrix-memory.svg",
		barChart("Rate range query: modeled peak memory by strategy", "peak memory (MiB)",
			labels, memVals, func(v float64) string { return fmtMiB(v) }))
	if err != nil {
		return err
	}
	fmt.Fprintf(b, "![Modeled peak memory by strategy](%s)\n\n", mref)

	// Narrative interpretation, pulled from the measured cells.
	renderMatrixNarrative(b, m)
	return nil
}

// renderMatrixNarrative interprets the three strategies in plain language,
// citing the measured cells so the prose can never drift from the numbers.
func renderMatrixNarrative(b *strings.Builder, m matrixResult) {
	single := matrixSingleCell(m)
	sharded := matrixShardedCell(m)
	native := matrixNativeCell(m)

	b.WriteString("**Reading the three strategies.**\n\n")

	if single != nil {
		fmt.Fprintf(b, "- **single = the baseline, and the problem.** The whole fan-out runs in "+
			"one statement: ~%s intermediate `(sample, anchor)` rows materialize before the "+
			"`GROUP BY` collapse (**modeled %s**). That is the single-query memory this whole "+
			"section is about reducing.\n",
			fmtInt(single.PeakRows), fmtBytes(single.PeakMem))
	}
	if single != nil && sharded != nil {
		fmt.Fprintf(b, "- **sharded = trade statement count for a lower per-query peak.** "+
			"Slicing into K=%d statements cuts the worst shard to ~%s rows (**modeled %s**) — a "+
			"**%.1f×** reduction in per-query peak memory, which is what fits it under the cap. "+
			"The shards run sequentially on this single in-process engine, so the *wall* here is "+
			"the conservative sum; in production they run on parallel ClickHouse connections.\n",
			sharded.K, fmtInt(sharded.PeakRows), fmtBytes(sharded.PeakMem),
			ratioI(single.PeakRows, sharded.PeakRows))
	}
	if native != nil && single != nil {
		fmt.Fprintf(b, "- **native rate = remove the fan-out at the source.** With "+
			"`timeSeriesRateToGrid` on, the intermediate drops from ~%s rows to ~%s "+
			"(**modeled %s**, down from %s) — the aggregate never builds the `(sample, anchor)` "+
			"matrix at all, so it collapses to a single-pass statement and the execution route "+
			"is moot. Where sharding makes the fan-out *fit*, the native path makes it "+
			"*vanish*.\n",
			fmtInt(single.PeakRows), fmtInt(native.PeakRows),
			fmtBytes(native.PeakMem), fmtBytes(single.PeakMem))
	}
	b.WriteString("\n")
	b.WriteString("So the two remedies do not compose into a four-way grid — they are a choice. ")
	b.WriteString("`auto` routing keeps any deployment safe under the memory cap today by ")
	b.WriteString("sharding the fan-out; turning the native-rate flag on collapses the fan-out at ")
	b.WriteString("its source for the deployments whose ClickHouse is new enough, at which point ")
	b.WriteString("there is nothing left to shard. The ")
	b.WriteString("[sharded solver section](#sharded-solver-the-memory-cap-win) below works the ")
	b.WriteString("memory arithmetic against the real production cap.\n\n")
}

// renderSharded keeps the OOM-class memory story, retold as a follow-on to
// the matrix rather than the lead.
func renderSharded(b *strings.Builder, in docInput) {
	sh := in.sharded
	b.WriteString("## Sharded solver: the memory-cap win\n\n")

	b.WriteString("The matrix showed *that* sharding cuts per-query memory; this section shows it ")
	b.WriteString("against the **real production cap**. ClickHouse data-plane queries run under a ")
	fmt.Fprintf(b, "**%s** per-query memory limit (`CERBERUS_CH_QUERY_MAX_MEMORY`). A high-fan-out "+
		"matrix range query can exceed it in a single statement — the failure mode the "+
		"[sharded-pushdown solver](solver.md) exists to prevent.\n\n", fmtBytes(sh.CapBytes))

	fmt.Fprintf(b, "**The fixture.** `%s` @ %s over %s — fan-out F = **%d**, grid N = **%d**. "+
		"Seeded with **%s** series and **%s** scanned samples, sized so a single statement "+
		"crosses the cap while every shard stays under it.\n\n",
		sh.Query, fmtGridDur(sh.Step), fmtGridDur(sh.OuterRange), sh.F, sh.N,
		fmtInt(sh.Series), fmtInt(sh.ScanRows))

	routeAClears := sh.RouteAModeledBytes <= sh.CapBytes
	maxShardClears := sh.MaxShardModeledBytes <= sh.CapBytes
	rows := [][]string{
		{"A — single statement", "1", fmtInt(sh.RouteAPairs), fmtBytes(sh.RouteAModeledBytes), verdict(routeAClears)},
		{
			fmt.Sprintf("B — sharded (K=%d)", sh.K), fmt.Sprintf("%d", sh.K),
			fmtInt(sh.MaxShardPairs) + " (max)", fmtBytes(sh.MaxShardModeledBytes), verdict(maxShardClears),
		},
	}
	writeTable(b, []align{alignLeft, alignRight, alignRight, alignRight, alignLeft},
		[]string{"route", "statements", "(sample,anchor) pairs", "modeled peak", "vs " + fmtBytes(sh.CapBytes) + " cap"},
		rows)
	b.WriteString("\n")

	routeACmp := "**exceeds** the cap"
	if routeAClears {
		routeACmp = "sits under the cap"
	}
	fmt.Fprintf(b, "Route A's modeled peak (**%s**) %s; every route-B shard's modeled peak (**%s**) "+
		"sits under it with **%.1f× headroom**. The shards partition route A's work exactly — the "+
		"per-shard pair counts sum to route A's total (%s), with no double-count — so the worst "+
		"shard carries ~1/K of the fan-out, a **%.1f×** reduction.\n\n",
		fmtBytes(sh.RouteAModeledBytes), routeACmp, fmtBytes(sh.MaxShardModeledBytes),
		float64(sh.CapBytes)/float64(sh.MaxShardModeledBytes),
		fmtInt(sh.SumShardPairs), ratioI(sh.RouteAPairs, sh.MaxShardPairs))

	b.WriteString("> **On \"modeled.\"** The `(sample, anchor)` pair count is **measured live on ")
	b.WriteString("chDB** — it is the deterministic driver of per-statement memory (the matrix ")
	b.WriteString("`arrayJoin` materializes one row per pair before the `GROUP BY` collapse). The ")
	b.WriteString("**GiB are modeled**: chDB never OOMs, so the pair counts are scaled by one ")
	fmt.Fprintf(b, "published calibration constant — a worked spike's 2.12 GiB at ≈100.4M pairs "+
		"(≈%.0f B/pair). The measured pair-count reduction is the real, deterministic result; the "+
		"GiB framing maps it onto the cap the design respects.\n\n", bytesPerPair())

	if len(sh.ShardPairs) > 0 {
		b.WriteString("Per-shard measured pairs (oldest-first): ")
		parts := make([]string, len(sh.ShardPairs))
		for i, p := range sh.ShardPairs {
			parts[i] = fmt.Sprintf("shard %d = %s", i, fmtInt(p))
		}
		b.WriteString(strings.Join(parts, ", ") + ".\n\n")
	}
}

// verdict renders the cap-fit verdict for the sharded table.
func verdict(clears bool) string {
	if clears {
		return "clears"
	}
	return "**OOM** (exceeds cap)"
}

// renderScaling — wall vs cardinality with the line chart.
func renderScaling(b *strings.Builder, in docInput) error {
	b.WriteString("## Scaling: wall vs cardinality\n\n")
	b.WriteString("A query optimization is only durable if it stays bounded as the data grows. ")
	b.WriteString("Each registered construct (`test/perf/scaling/`) is swept across a growing ")
	b.WriteString("fan-out parameter, holding the scan size fixed, and we watch two things: the ")
	b.WriteString("wall time, and `fan_factor` — the peak intermediate cardinality divided by the ")
	b.WriteString("scan rows. A bounded shape keeps `fan_factor` roughly flat as the parameter ")
	b.WriteString("grows: the intermediate stays a small constant multiple of the scan, never ")
	b.WriteString("`rows × parameter`.\n\n")

	for _, c := range in.curves {
		fmt.Fprintf(b, "### %s — sweep %s\n\n", c.Name, c.Param)
		fmt.Fprintf(b, "Scan rows held fixed at %s.\n\n", fmtInt(c.ScanRows))
		var rows [][]string
		var pts []linePoint
		for _, p := range c.Points {
			rows = append(rows, []string{
				fmt.Sprintf("%d", p.Param), roundDur(p.Wall),
				fmtInt(p.PeakRows), fmt.Sprintf("%.2f", p.FanRatio),
			})
			pts = append(pts, linePoint{
				X:     float64(p.Param),
				Y:     float64(p.Wall) / float64(time.Millisecond),
				Label: fmt.Sprintf("%d", p.Param),
			})
		}
		writeTable(b, []align{alignRight, alignRight, alignRight, alignRight},
			[]string{"param", "wall", "peak rows", "fan_factor"}, rows)
		b.WriteString("\n")

		ref, err := writeChart(in.outPath, "scaling-"+c.Name+".svg",
			lineChart(fmt.Sprintf("%s: wall vs %s", c.Name, c.Param),
				c.Param, "wall (ms)", pts, func(v float64) string { return fmtMs(v) }))
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "![%s scaling](%s)\n\n", c.Name, ref)

		fmt.Fprintf(b, "Parameter grew **%.1f×** across the sweep; wall grew **%.1f×** ",
			c.ParamGrowth, c.WallGrowth)
		if c.WallGrowth < c.ParamGrowth {
			b.WriteString("(sub-linear). ")
		} else {
			b.WriteString("(tracks the parameter — see the note below). ")
		}
		fmt.Fprintf(b, "`fan_factor` stayed bounded (%.2f → %.2f).\n\n",
			c.Points[0].FanRatio, c.Points[len(c.Points)-1].FanRatio)
	}

	b.WriteString("> **Note.** The `setop_chain` curve runs through the optimizer, so the ")
	b.WriteString("`FlattenVectorSetOp` rule collapses the left-assoc `a or b or c …` nesting into ")
	b.WriteString("one N-ary `UNION ALL` under a single window pass — the chain is one scan, not K ")
	b.WriteString("nested window passes, so **both** the wall and the cardinality axis are flat in ")
	b.WriteString("chain depth and the harness hard-gates both. (`unless` is not associative, so an ")
	b.WriteString("`unless` chain keeps its binary nesting by construction.)\n\n")
	return nil
}

// renderHeadlines — the per-optimization before/after wins, demoted below the
// e2e + matrix story but kept in full.
func renderHeadlines(b *strings.Builder, in docInput) {
	b.WriteString("## Optimizer before/after wins\n\n")
	b.WriteString("Cerberus's optimizer rewrites each plan before emission. These are the ")
	b.WriteString("individual wins, each pairing the **naive** pre-optimization SQL against the ")
	b.WriteString("**optimized** shape cerberus actually emits, both run live on chDB. The `win` ")
	b.WriteString("column is the deterministic structural ratio where one exists (granules read, ")
	b.WriteString("rows scanned, peak cardinality), else the indicative wall-time speedup.\n\n")

	var rows [][]string
	for _, w := range in.wins {
		ratio, basis := headlineRatio(w)
		rows = append(rows, []string{w.Name, fmt.Sprintf("%.1f×", ratio), basis})
	}
	writeTable(b, []align{alignLeft, alignRight, alignLeft},
		[]string{"optimization", "win", "basis"}, rows)
	b.WriteString("\n")

	for _, w := range in.wins {
		fmt.Fprintf(b, "### %s\n\n", w.Name)
		fmt.Fprintf(b, "- **Scenario:** %s\n", w.Param)
		fmt.Fprintf(b, "- **Naive:** %s\n", w.Naive)
		fmt.Fprintf(b, "- **Optimized:** %s\n", w.Optimized)
		if w.StructRatio > 0 {
			fmt.Fprintf(b, "- **%s (deterministic):** %s → %s (**%.1f× fewer**)\n",
				w.StructLabel, fmtInt(w.NaiveStruct), fmtInt(w.OptStruct), w.StructRatio)
		}
		if w.WallNote != "" {
			fmt.Fprintf(b, "- **Wall (indicative):** %s → %s — %s\n",
				roundDur(w.NaiveWall), roundDur(w.OptWall), w.WallNote)
		} else {
			fmt.Fprintf(b, "- **Wall (indicative):** %s → %s (**%.1f× faster**)\n",
				roundDur(w.NaiveWall), roundDur(w.OptWall), w.Speedup)
		}
		b.WriteString("\n")
	}
}

// headlineRatio picks the headline ratio + a short basis label.
func headlineRatio(w headlineWin) (float64, string) {
	if w.Primary == "structural" && w.StructRatio > 0 {
		return w.StructRatio, w.StructLabel + " (deterministic)"
	}
	return w.Speedup, "wall time (indicative)"
}

// renderMicro — the per-component isolated costs.
func renderMicro(b *strings.Builder, in docInput) {
	b.WriteString("## Micro-benchmarks\n\n")
	b.WriteString("Per-stage Go benchmarks, no database involved — they isolate the cost of one ")
	b.WriteString("pipeline stage so an allocation regression in, say, lowering can't hide behind ")
	b.WriteString("a fast query. `allocs/op` and `B/op` are deterministic; `ns/op` is indicative. ")
	b.WriteString("Read the `package` column as the stage: `promql`/`logql`/`traceql` parse + ")
	b.WriteString("lower, `optimizer` rewrites the plan, `chsql` emits SQL, `chplan` is the IR, ")
	b.WriteString("`api/*` is the wire layer.\n\n")

	var rows [][]string
	for _, m := range in.micro {
		rows = append(rows, []string{
			m.Pkg, shortName(m.Name), fmtFloatNs(m.NsPerOp),
			fmtInt(m.BytesOp), fmt.Sprintf("%d", m.AllocsOp),
		})
	}
	writeTable(b, []align{alignLeft, alignLeft, alignRight, alignRight, alignRight},
		[]string{"package", "benchmark", "ns/op", "B/op", "allocs/op"}, rows)
	b.WriteString("\n")
}

// renderReproducing — the exact commands.
func renderReproducing(b *strings.Builder) {
	b.WriteString("## Reproducing\n\n")
	b.WriteString("The whole document — tables, numbers, and the SVG charts — is regenerated by ")
	b.WriteString("one command:\n\n")
	b.WriteString("```sh\njust chdb-install   # once: fetches libchdb.so (the embedded engine)\njust bench-report   # measures everything and rewrites this file in place\n```\n\n")
	b.WriteString("`bench-report` is a manually-run artifact, not a CI gate: it opens an in-process ")
	b.WriteString("chDB session, seeds the synthetic datasets server-side, drives every query ")
	b.WriteString("through the real lowering pipeline, measures, and writes `docs/benchmarks.md` ")
	b.WriteString("plus the charts under `docs/benchmarks/`. Re-run it whenever performance ")
	b.WriteString("changes and review the diff before committing.\n\n")
}

func renderSeeAlso(b *strings.Builder) {
	b.WriteString("## See also\n\n")
	b.WriteString("- [`docs/performance.md`](performance.md) — the optimizer + perf architecture ")
	b.WriteString("these numbers exercise.\n")
	b.WriteString("- [`docs/solver.md`](solver.md) — the sharded-pushdown solver (route B) in ")
	b.WriteString("full: eligibility, slicing geometry, the memory cap.\n")
	b.WriteString("- [`docs/test-strategy.md`](test-strategy.md) — the perf-assessment test layers ")
	b.WriteString("(scaling harness, corpus profiler, cardinality ratchet) that gate structural ")
	b.WriteString("regressions in CI.\n")
}

// --- matrix presentation helpers ----------------------------------------

// matrixRows builds the three-strategy table rows in presentation order:
// strategy | statements | wall | peak mem | note. The note conveys what each
// strategy does to the fan-out (baseline / cap-fit / removed).
func matrixRows(m matrixResult) [][]string {
	var rows [][]string
	for _, c := range m.Cells {
		stmts := "1"
		if c.Routed {
			stmts = fmt.Sprintf("%d", c.K)
		}
		rows = append(rows, []string{
			c.Name, stmts, roundDur(c.Wall), fmtBytes(c.PeakMem), matrixNote(c),
		})
	}
	return rows
}

// matrixNote describes a strategy's effect on the fan-out for the table's
// note column, derived from the measured cell (route + tsgrid).
func matrixNote(c matrixCell) string {
	switch {
	case c.TSGrid:
		return "fan-out removed (single-pass aggregate)"
	case c.Routed:
		return fmt.Sprintf("fan-out sliced to fit (K=%d shards)", c.K)
	default:
		return "baseline — whole fan-out in one query"
	}
}

// matrixChartData splits the cells into single-series bar inputs: one bar per
// strategy, for both wall (ms) and memory (MiB).
func matrixChartData(m matrixResult) (labels []string, wall, mem []float64) {
	for i := range m.Cells {
		c := &m.Cells[i]
		labels = append(labels, c.Name)
		wall = append(wall, cellWallMs(c))
		mem = append(mem, cellMemMiB(c))
	}
	return labels, wall, mem
}

func cellWallMs(c *matrixCell) float64 {
	if c == nil {
		return 0
	}
	return float64(c.Wall) / float64(time.Millisecond)
}

func cellMemMiB(c *matrixCell) float64 {
	if c == nil {
		return 0
	}
	return float64(c.PeakMem) / float64(1<<20)
}

// matrixSingleCell / matrixShardedCell / matrixNativeCell select the cell for
// each of the three strategies, identifying them by their (route, tsgrid)
// configuration so the narrative reads off the same measured numbers the
// table renders. Native rate is the tsgrid-on strategy regardless of route
// (auto collapses to single under it); the other two are tsgrid-off.
func matrixSingleCell(m matrixResult) *matrixCell {
	return matrixCellByConfig(m, solver.ModeSingle, false)
}

func matrixShardedCell(m matrixResult) *matrixCell {
	return matrixCellByConfig(m, solver.ModeSharded, false)
}

func matrixNativeCell(m matrixResult) *matrixCell {
	for i := range m.Cells {
		if m.Cells[i].TSGrid {
			return &m.Cells[i]
		}
	}
	return nil
}

// matrixCellByConfig finds the cell for a (route, tsgrid) pair, or nil.
func matrixCellByConfig(m matrixResult, route string, tsgrid bool) *matrixCell {
	for i := range m.Cells {
		if m.Cells[i].Route == route && m.Cells[i].TSGrid == tsgrid {
			return &m.Cells[i]
		}
	}
	return nil
}

// e2eShortLabel trims an e2e row name to a compact chart x-label.
func e2eShortLabel(name string) string {
	switch {
	case strings.HasPrefix(name, "range query"):
		return "rate range"
	case strings.HasPrefix(name, "instant"):
		return "instant"
	case strings.HasPrefix(name, "series"):
		return "series"
	case strings.HasPrefix(name, "TraceQL"):
		return "TraceQL"
	case strings.HasPrefix(name, "LogQL"):
		return "LogQL"
	}
	return name
}

// --- formatting helpers --------------------------------------------------

// roundDur rounds a duration to a stable, low-noise unit.
func roundDur(d time.Duration) string {
	switch {
	case d < time.Microsecond:
		return d.String()
	case d < time.Millisecond:
		return fmt.Sprintf("%dµs", d.Round(time.Microsecond)/time.Microsecond)
	case d < time.Second:
		return fmt.Sprintf("%.1fms", float64(d)/float64(time.Millisecond))
	default:
		return fmt.Sprintf("%.2fs", d.Seconds())
	}
}

// fmtMs renders a chart value already in milliseconds with a compact unit.
func fmtMs(ms float64) string {
	switch {
	case ms >= 1000:
		return fmt.Sprintf("%.2fs", ms/1000)
	case ms >= 100:
		return fmt.Sprintf("%.0fms", ms)
	case ms >= 10:
		return fmt.Sprintf("%.1fms", ms)
	default:
		return fmt.Sprintf("%.1fms", ms)
	}
}

// fmtMiB renders a chart value already in MiB.
func fmtMiB(mib float64) string {
	if mib >= 1024 {
		return fmt.Sprintf("%.2fGiB", mib/1024)
	}
	return fmt.Sprintf("%.0fMiB", mib)
}

// fmtGridDur renders a grid duration in the natural PromQL unit.
func fmtGridDur(d time.Duration) string {
	switch {
	case d == 0:
		return "0s"
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	case d%time.Second == 0:
		return fmt.Sprintf("%ds", d/time.Second)
	default:
		return d.String()
	}
}

// fmtBytes renders a byte count as a readable binary size.
func fmtBytes(n int64) string {
	const (
		kib = 1 << 10
		mib = 1 << 20
		gib = 1 << 30
	)
	switch {
	case n >= gib:
		return fmt.Sprintf("%.2f GiB", float64(n)/float64(gib))
	case n >= mib:
		return fmt.Sprintf("%d MiB", (n+mib/2)/mib)
	case n >= kib:
		return fmt.Sprintf("%d KiB", (n+kib/2)/kib)
	default:
		return fmt.Sprintf("%d B", n)
	}
}

// fmtInt renders an int with thousands separators.
func fmtInt(n int64) string {
	neg := n < 0
	if neg {
		n = -n
	}
	s := fmt.Sprintf("%d", n)
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	if neg {
		return "-" + string(out)
	}
	return string(out)
}

// fmtFloatNs rounds ns/op to whole ns.
func fmtFloatNs(f float64) string {
	if f <= 0 {
		return "—"
	}
	return fmtInt(int64(f + 0.5))
}

// shortName truncates a long benchmark name.
func shortName(s string) string {
	const maxLen = 40
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-1] + "…"
}
