//go:build chdb

package main

import (
	"fmt"
	"strings"
	"time"
	"unicode/utf8"
)

type docInput struct {
	wins    []headlineWin
	curves  []scalingCurve
	sharded shardedResult
	e2e     []e2eResult
	micro   []microResult

	iters     int
	benchtime string

	metricRows, logRows, traceRows int64

	goVersion string
	goarch    string
	numCPU    int
}

// align enumerates a markdown table column's alignment for the separator
// row and cell padding.
type align int

const (
	alignLeft align = iota
	alignRight
)

// writeTable emits a markdownlint-MD060-compliant aligned table: every
// pipe lines up because each cell is padded to its column's max width.
// aligns gives the per-column alignment (left/right); header + rows must
// all have len(aligns) cells.
func writeTable(b *strings.Builder, aligns []align, header []string, rows [][]string) {
	widths := make([]int, len(aligns))
	for i, h := range header {
		widths[i] = utf8.RuneCountInString(h)
	}
	for _, r := range rows {
		for i, c := range r {
			if w := utf8.RuneCountInString(c); w > widths[i] {
				widths[i] = w
			}
		}
	}
	// The separator cell is `---`/`---:`; ensure the column is wide enough
	// for it (min 3, +1 for the right-align colon).
	for i, a := range aligns {
		min := 3
		if a == alignRight {
			min = 4
		}
		if widths[i] < min {
			widths[i] = min
		}
	}

	writeRow := func(cells []string) {
		b.WriteString("|")
		for i, c := range cells {
			pad := widths[i] - utf8.RuneCountInString(c)
			if aligns[i] == alignRight {
				b.WriteString(" " + strings.Repeat(" ", pad) + c + " |")
			} else {
				b.WriteString(" " + c + strings.Repeat(" ", pad) + " |")
			}
		}
		b.WriteString("\n")
	}
	writeRow(header)
	// separator
	b.WriteString("|")
	for i, a := range aligns {
		if a == alignRight {
			b.WriteString(" " + strings.Repeat("-", widths[i]-1) + ": |")
		} else {
			b.WriteString(" " + strings.Repeat("-", widths[i]) + " |")
		}
	}
	b.WriteString("\n")
	for _, r := range rows {
		writeRow(r)
	}
}

// renderDoc assembles the full benchmarks.md. Timings are rounded to
// reduce single-process noise; ratios (the stable signal) carry one
// decimal. Tables are emitted via writeTable so pipes align (MD060).
func renderDoc(in docInput) string {
	var b strings.Builder

	b.WriteString("# Cerberus benchmarks\n\n")
	b.WriteString("Live performance measurements for the cerberus query gateway: optimizer ")
	b.WriteString("before/after wins, the **sharded-solver** memory-unbounded win, scaling ")
	b.WriteString("curves, per-stage micro-benchmarks, and end-to-end query latency on a ")
	b.WriteString("realistic dataset. Every number here is **measured**, not estimated — the ")
	b.WriteString("document is regenerated by ")
	b.WriteString("[`just bench-report`](#methodology--how-to-regenerate).\n\n")

	renderTopline(&b, in)
	renderMethodology(&b, in)
	renderHeadlines(&b, in)
	renderSharded(&b, in)
	renderScaling(&b, in)
	renderMicro(&b, in)
	renderE2E(&b, in)

	b.WriteString("## See also\n\n")
	b.WriteString("- [`docs/performance.md`](performance.md) — the optimizer + perf ")
	b.WriteString("architecture these numbers exercise.\n")
	b.WriteString("- [`docs/test-strategy.md`](test-strategy.md) — the perf-assessment ")
	b.WriteString("test layers (scaling harness, corpus profiler, cardinality ratchet) ")
	b.WriteString("that gate structural regressions in CI.\n")

	return b.String()
}

// renderTopline puts the headline at the very top: a one-line summary row per
// dimension, led by the sharded-solver win (the OOM-class range query route A
// cannot serve under the 1 GiB cap that route B clears). It lets a reader see
// the wins before scrolling into the per-dimension detail.
func renderTopline(b *strings.Builder, in docInput) {
	b.WriteString("## At a glance\n\n")

	sh := in.sharded
	var rows [][]string
	// Lead row: the sharded-solver headline. The route-A verdict is derived,
	// not asserted — if a seed resize ever dropped route A under the cap, the
	// doc would say so rather than lie.
	routeAVerdict := "OOM"
	if sh.RouteAModeledBytes <= sh.CapBytes {
		routeAVerdict = "fits"
	}
	rows = append(rows, []string{
		"sharded solver (OOM class)",
		fmt.Sprintf("%.1f×", ratioI(sh.RouteAPairs, sh.MaxShardPairs)),
		fmt.Sprintf("route A %s modeled (%s vs %s cap) → route B K=%d, %s/shard (clears)",
			fmtBytes(sh.RouteAModeledBytes), routeAVerdict, fmtBytes(sh.CapBytes), sh.K, fmtBytes(sh.MaxShardModeledBytes)),
	})
	// Then the top structural optimizer win.
	for _, w := range in.wins {
		ratio, basis := headlineRatio(w)
		rows = append(rows, []string{w.Name, fmt.Sprintf("%.1f×", ratio), basis})
	}
	writeTable(b, []align{alignLeft, alignRight, alignLeft},
		[]string{"dimension", "win", "what it measures"}, rows)
	b.WriteString("\n")

	overVerb := "**OOMs**, over"
	if sh.RouteAModeledBytes <= sh.CapBytes {
		overVerb = "fits under"
	}
	fmt.Fprintf(b, "The **sharded solver** is the headline: a high-fan-out matrix range query "+
		"(`%s` @ %s over %s, F=%d, N=%d) expands ≈%s (sample, anchor) pairs in a single "+
		"statement — a **modeled %s** that %s the **%s** per-query cap "+
		"(`CERBERUS_CH_QUERY_MAX_MEMORY`). The solver re-anchors the same "+
		"optimized plan onto **K=%d** disjoint anchor-grid shards; the worst shard expands "+
		"only ≈%s pairs (**modeled %s**) — every shard **clears** the cap with headroom. "+
		"See [Sharded solver](#sharded-solver--the-oom-class-win).\n\n",
		sh.Query, fmtGridDur(sh.Step), fmtGridDur(sh.OuterRange), sh.F, sh.N,
		fmtInt(sh.RouteAPairs), fmtBytes(sh.RouteAModeledBytes), overVerb, fmtBytes(sh.CapBytes),
		sh.K, fmtInt(sh.MaxShardPairs), fmtBytes(sh.MaxShardModeledBytes))
}

func renderMethodology(b *strings.Builder, in docInput) {
	b.WriteString("## Methodology / how to regenerate\n\n")
	b.WriteString("```sh\njust bench-report\n```\n\n")
	b.WriteString("Regenerates this file in place. Requires `libchdb.so` (`just chdb-install`) — ")
	b.WriteString("all measurements run in-process against an embedded chDB ClickHouse engine, ")
	b.WriteString("and the optimized SQL shapes are produced by driving real queries through ")
	b.WriteString("the cerberus lowering pipeline (`internal/{promql,logql,traceql}` → ")
	b.WriteString("`internal/chsql`), so the measured SQL is the SQL cerberus emits.\n\n")

	b.WriteString("**Determinism.** Structural metrics — fan_factor, peak intermediate ")
	b.WriteString("cardinality, granules read, `allocs/op` — are deterministic and committed ")
	b.WriteString("verbatim. Timings — `ns/op`, wall-ms, e2e latency — are machine-dependent; ")
	b.WriteString("they are presented as **speedup ratios** wherever a before/after exists ")
	b.WriteString("(stable across hardware) and labelled *indicative* where absolute. This ")
	b.WriteString("document is a manually-regenerated artifact, **not** a CI gate: no test ")
	b.WriteString("fails on timing drift. Structural regressions are guarded separately by ")
	b.WriteString("the cardinality ratchet (`test/perf/cardinality_ratchet_test.go`) and the ")
	b.WriteString("scaling harness (`test/perf/scaling/`).\n\n")

	fmt.Fprintf(b, "**Sample count.** Each chDB wall timing is best-of-%d (the floor strips ", in.iters)
	fmt.Fprintf(b, "GC / scheduler jitter); micro-benchmarks use `-benchtime %s`.\n\n", in.benchtime)

	fmt.Fprintf(b, "**Reference hardware.** Indicative timings measured on `%s` / `%s` / ",
		in.goVersion, in.goarch)
	fmt.Fprintf(b, "%d logical CPUs. Treat absolute timings as order-of-magnitude; ratios are portable.\n\n",
		in.numCPU)
}

func renderHeadlines(b *strings.Builder, in docInput) {
	b.WriteString("## Headline before/after wins\n\n")
	b.WriteString("Each win pairs the **naive** pre-optimization SQL shape against the ")
	b.WriteString("**optimized** shape cerberus actually emits, both run live on chDB over a ")
	b.WriteString("seeded dataset. The `win` column is the headline ratio: a deterministic ")
	b.WriteString("structural ratio where one exists (granules read, rows scanned, peak ")
	b.WriteString("intermediate cardinality), else the indicative wall-time speedup. The ")
	b.WriteString("per-win detail below carries both axes.\n\n")

	var rows [][]string
	for _, w := range in.wins {
		ratio, basis := headlineRatio(w)
		rows = append(rows, []string{w.Name, fmt.Sprintf("%.1f×", ratio), basis})
	}
	writeTable(b, []align{alignLeft, alignRight, alignLeft},
		[]string{"optimization", "win", "basis"}, rows)
	b.WriteString("\n")

	// Per-win detail as a list (long descriptions go here, not in cells).
	for _, w := range in.wins {
		fmt.Fprintf(b, "### %s\n\n", w.Name)
		fmt.Fprintf(b, "- **Scenario:** %s\n", w.Param)
		fmt.Fprintf(b, "- **Naive:** %s\n", w.Naive)
		fmt.Fprintf(b, "- **Optimized:** %s\n", w.Optimized)
		if w.StructRatio > 0 {
			fmt.Fprintf(b, "- **%s (deterministic):** %s → %s (**%.1f× fewer**)\n",
				w.StructLabel, fmtInt(w.NaiveStruct), fmtInt(w.OptStruct), w.StructRatio)
		}
		if w.WallNote != "" {
			fmt.Fprintf(b, "- **Wall (indicative):** %s → %s — %s\n",
				roundDur(w.NaiveWall), roundDur(w.OptWall), w.WallNote)
		} else {
			fmt.Fprintf(b, "- **Wall (indicative):** %s → %s (**%.1f× faster**)\n",
				roundDur(w.NaiveWall), roundDur(w.OptWall), w.Speedup)
		}
		b.WriteString("\n")
	}
}

// headlineRatio picks the headline ratio + a short basis label for the
// summary table, honouring each win's Primary axis.
func headlineRatio(w headlineWin) (float64, string) {
	if w.Primary == "structural" && w.StructRatio > 0 {
		return w.StructRatio, w.StructLabel + " (deterministic)"
	}
	return w.Speedup, "wall time (indicative)"
}

// renderSharded emits the SHARDED-SOLVER dimension: the OOM-class range query
// route A cannot serve under the 1 GiB per-query cap, that route B (the sharded
// solver) clears. The table contrasts route A (single statement, whole anchor
// grid) against route B (K shards, each its anchor sub-grid) on the MEASURED
// expanded (sample, anchor) pair count — the deterministic driver of
// per-statement memory — plus the MODELED GiB derived from it against the cap.
func renderSharded(b *strings.Builder, in docInput) {
	sh := in.sharded
	b.WriteString("## Sharded solver — the OOM-class win\n\n")

	fmt.Fprintf(b, "The sharded-pushdown solver (`internal/solver`, ")
	b.WriteString("[`docs/query-solver-design.md`](query-solver-design.md)) recognizes the narrow ")
	b.WriteString("class of range queries whose **single-statement** execution is memory-unbounded ")
	b.WriteString("on ClickHouse — a high anchor fan-out `F = Range/Step` matrix shape — and ")
	b.WriteString("re-anchors the *same* optimized plan onto **K disjoint anchor-grid shards**, ")
	b.WriteString("each running the identical compat-gated SQL restricted to its anchor sub-grid. ")
	b.WriteString("No new evaluator, no new SQL template.\n\n")

	fmt.Fprintf(b, "**Fixture (OOM class).** `%s` @ %s over %s — F = Range/Step = **%d**, "+
		"N = OuterRange/Step + 1 = **%d**. Seeded: **%s** series, **%s** scanned samples "+
		"(one sample / %s across the input window, generated server-side via `numbers(N)`).\n\n",
		sh.Query, fmtGridDur(sh.Step), fmtGridDur(sh.OuterRange), sh.F, sh.N,
		fmtInt(sh.Series), fmtInt(sh.ScanRows), fmtGridDur(sh.Step))

	// The contrast table.
	routeAClears := sh.RouteAModeledBytes <= sh.CapBytes
	maxShardClears := sh.MaxShardModeledBytes <= sh.CapBytes
	rows := [][]string{
		{
			"A — single statement",
			"1",
			fmtInt(sh.RouteAPairs),
			fmtBytes(sh.RouteAModeledBytes),
			verdict(routeAClears),
		},
		{
			fmt.Sprintf("B — sharded (K=%d)", sh.K),
			fmt.Sprintf("%d", sh.K),
			fmtInt(sh.MaxShardPairs) + " (max)",
			fmtBytes(sh.MaxShardModeledBytes),
			verdict(maxShardClears),
		},
	}
	writeTable(b, []align{alignLeft, alignRight, alignRight, alignRight, alignLeft},
		[]string{"route", "statements", "(sample,anchor) pairs", "modeled peak", "vs " + fmtBytes(sh.CapBytes) + " cap"},
		rows)
	b.WriteString("\n")

	routeACmp := "**exceeds** it — the OOM 422 the k3d run that motivated the cap actually hit"
	if routeAClears {
		routeACmp = "sits under it"
	}
	fmt.Fprintf(b, "- **Cap.** The prod per-query memory cap is **%s** "+
		"(`CERBERUS_CH_QUERY_MAX_MEMORY`, the default `chclient` stamps on every data-plane "+
		"query). Route A's modeled peak (**%s**) %s. Every route-B shard's modeled peak (**%s**) "+
		"sits **under** the cap (**%.1f× headroom**).\n",
		fmtBytes(sh.CapBytes), fmtBytes(sh.RouteAModeledBytes), routeACmp, fmtBytes(sh.MaxShardModeledBytes),
		float64(sh.CapBytes)/float64(sh.MaxShardModeledBytes))
	fmt.Fprintf(b, "- **Pairs are MEASURED.** The (sample, anchor) pair count is the deterministic "+
		"driver of per-statement memory: the matrix `arrayJoin` fan-out materializes one row "+
		"per (sample, covered anchor) before the `GROUP BY` collapse. It is counted **live on "+
		"chDB** over the seed — route A over the whole %d-anchor grid, each shard over only its "+
		"sub-grid. The K shards partition route A's pairs exactly: Σ per-shard = %s = route-A "+
		"%s (no double-count), and the worst shard carries %s — a **%.1f×** reduction, tracking "+
		"1/K.\n",
		sh.N, fmtInt(sh.SumShardPairs), fmtInt(sh.RouteAPairs), fmtInt(sh.MaxShardPairs),
		ratioI(sh.RouteAPairs, sh.MaxShardPairs))
	fmt.Fprintf(b, "- **GiB are MODELED, not measured.** chDB does **not** enforce a memory cap "+
		"(it coerces leniently and never OOMs), so this dimension does **not** claim a measured "+
		"OOM. The modeled-peak columns scale the **measured** pair counts by a single published "+
		"calibration constant — the worked spike's 2.12 GiB at ≈100.4M pairs "+
		"(≈%.1f B/pair, k3d run 27277793810). The honest claim: the **measured** pair-count "+
		"reduction is real and deterministic; the GiB framing maps it onto the prod cap the "+
		"design exists to respect.\n", bytesPerPair())

	// Per-shard pair breakdown (a list, so MD060 stays clean for long rows).
	if len(sh.ShardPairs) > 0 {
		b.WriteString("\nPer-shard measured pairs (oldest-first): ")
		parts := make([]string, len(sh.ShardPairs))
		for i, p := range sh.ShardPairs {
			parts[i] = fmt.Sprintf("shard %d = %s", i, fmtInt(p))
		}
		b.WriteString(strings.Join(parts, ", ") + ".\n\n")
	}
}

// verdict renders the cap-fit verdict for the sharded table.
func verdict(clears bool) string {
	if clears {
		return "clears"
	}
	return "**OOM** (exceeds cap)"
}

func renderScaling(b *strings.Builder, in docInput) {
	b.WriteString("## Scaling curves\n\n")
	b.WriteString("Wall-time and `fan_factor` (peak intermediate cardinality ÷ scan rows) vs ")
	b.WriteString("the real fan-out multiplier for each registered construct ")
	b.WriteString("(`test/perf/scaling/`). A bounded shape keeps `fan_factor` ~flat as the ")
	b.WriteString("parameter grows — the cardinality stays a small constant multiple of the ")
	b.WriteString("scan, never `rows × parameter`.\n\n")

	for _, c := range in.curves {
		fmt.Fprintf(b, "### %s — sweep %s\n\n", c.Name, c.Param)
		fmt.Fprintf(b, "Scan rows held fixed at %s.\n\n", fmtInt(c.ScanRows))
		var rows [][]string
		for _, p := range c.Points {
			rows = append(rows, []string{
				fmt.Sprintf("%d", p.Param), roundDur(p.Wall),
				fmtInt(p.PeakRows), fmt.Sprintf("%.2f", p.FanRatio),
			})
		}
		writeTable(b, []align{alignRight, alignRight, alignRight, alignRight},
			[]string{"param", "wall", "peak rows", "fan_factor"}, rows)
		fmt.Fprintf(b, "\nParameter grew **%.1f×** across the sweep; wall grew **%.1f×** ",
			c.ParamGrowth, c.WallGrowth)
		if c.WallGrowth < c.ParamGrowth {
			b.WriteString("(sub-linear). ")
		} else {
			b.WriteString("(tracks the parameter — see the residual finding below). ")
		}
		fmt.Fprintf(b, "`fan_factor` stayed bounded (%.2f → %.2f).\n\n",
			c.Points[0].FanRatio, c.Points[len(c.Points)-1].FanRatio)
	}

	b.WriteString("> Note: the `setop_chain` wall is the documented residual super-linearity ")
	b.WriteString("(each `or` level re-scans the accumulated relation; the cardinality axis is ")
	b.WriteString("flat). It is quarantined as a tracked finding in the scaling harness ")
	b.WriteString("(N-ary single-pass flatten is the fix); the harness still hard-gates the ")
	b.WriteString("cardinality axis.\n\n")
}

func renderMicro(b *strings.Builder, in docInput) {
	b.WriteString("## Micro-benchmarks\n\n")
	b.WriteString("Per-stage Go benchmarks across the pipeline. `allocs/op` is deterministic; ")
	b.WriteString("`ns/op` is indicative.\n\n")

	var rows [][]string
	for _, m := range in.micro {
		rows = append(rows, []string{
			m.Pkg, shortName(m.Name), fmtFloatNs(m.NsPerOp),
			fmtInt(m.BytesOp), fmt.Sprintf("%d", m.AllocsOp),
		})
	}
	writeTable(b, []align{alignLeft, alignLeft, alignRight, alignRight, alignRight},
		[]string{"package", "benchmark", "ns/op", "B/op", "allocs/op"}, rows)
	b.WriteString("\n")
}

func renderE2E(b *strings.Builder, in docInput) {
	b.WriteString("## End-to-end query latency\n\n")
	fmt.Fprintf(b, "Representative queries lowered + emitted through the real cerberus ")
	b.WriteString("pipeline and executed on a large synthetic OTel dataset: ")
	fmt.Fprintf(b, "**%s** metric samples, **%s** log records, **%s** spans ",
		fmtInt(in.metricRows), fmtInt(in.logRows), fmtInt(in.traceRows))
	b.WriteString("(generated server-side via `numbers(N)`). Latency is best-of-")
	fmt.Fprintf(b, "%d (indicative).\n\n", in.iters)

	var rows [][]string
	for _, r := range in.e2e {
		rows = append(rows, []string{r.Name, r.Head, fmtInt(r.ScanRows), roundDur(r.Wall)})
	}
	writeTable(b, []align{alignLeft, alignLeft, alignRight, alignRight},
		[]string{"query", "head", "scan rows", "latency"}, rows)
	b.WriteString("\nQuery shapes:\n\n")
	for _, r := range in.e2e {
		fmt.Fprintf(b, "- **%s** (`%s`): `%s`\n", r.Name, r.Head, r.Query)
	}
	b.WriteString("\n")
}

// --- formatting helpers --------------------------------------------------

// roundDur rounds a duration to a stable, low-noise unit: µs under 1ms,
// ms under 1s, else 2-decimal seconds. Keeps regenerated diffs small.
func roundDur(d time.Duration) string {
	switch {
	case d < time.Microsecond:
		return d.String()
	case d < time.Millisecond:
		return fmt.Sprintf("%dµs", d.Round(time.Microsecond)/time.Microsecond)
	case d < time.Second:
		return fmt.Sprintf("%.1fms", float64(d)/float64(time.Millisecond))
	default:
		return fmt.Sprintf("%.2fs", d.Seconds())
	}
}

// fmtGridDur renders a grid duration (Step / OuterRange / Range) in the
// natural PromQL unit — 1h / 5m / 15s — instead of roundDur's noisy
// "3600.00s". Whole-unit durations only (grid params always are).
func fmtGridDur(d time.Duration) string {
	switch {
	case d == 0:
		return "0s"
	case d%time.Hour == 0:
		return fmt.Sprintf("%dh", d/time.Hour)
	case d%time.Minute == 0:
		return fmt.Sprintf("%dm", d/time.Minute)
	case d%time.Second == 0:
		return fmt.Sprintf("%ds", d/time.Second)
	default:
		return d.String()
	}
}

// fmtBytes renders a byte count as a readable binary size (GiB / MiB / KiB),
// 2 decimals for GiB, whole numbers below. Keeps the modeled-memory columns
// stable and aligned (MD060).
func fmtBytes(n int64) string {
	const (
		kib = 1 << 10
		mib = 1 << 20
		gib = 1 << 30
	)
	switch {
	case n >= gib:
		return fmt.Sprintf("%.2f GiB", float64(n)/float64(gib))
	case n >= mib:
		return fmt.Sprintf("%d MiB", (n+mib/2)/mib)
	case n >= kib:
		return fmt.Sprintf("%d KiB", (n+kib/2)/kib)
	default:
		return fmt.Sprintf("%d B", n)
	}
}

// fmtInt renders an int with thousands separators for readability.
func fmtInt(n int64) string {
	neg := n < 0
	if neg {
		n = -n
	}
	s := fmt.Sprintf("%d", n)
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	if neg {
		return "-" + string(out)
	}
	return string(out)
}

// fmtFloatNs rounds ns/op to whole ns (sub-ns precision is noise).
func fmtFloatNs(f float64) string {
	if f <= 0 {
		return "—"
	}
	return fmtInt(int64(f + 0.5))
}

// shortName truncates a long benchmark name to keep MD060 table columns
// manageable.
func shortName(s string) string {
	const max = 40
	if len(s) <= max {
		return s
	}
	return s[:max-1] + "…"
}
